import type { ContentArea } from "../../types";
import type { ComponentKey } from "./types";

export const COMPONENT_REGISTRY: { key: ComponentKey; label: string; description?: string }[] = [
  { key: "Accordion", label: "Accordion" },
  { key: "ActionList", label: "Action List" },
  { key: "Avatar", label: "Avatar" },
  { key: "AvatarGroup", label: "Avatar Group" },
  { key: "Banner", label: "Banner" },
  { key: "Blockquote", label: "Blockquote" },
  { key: "Breadcrumb", label: "Breadcrumb" },
  { key: "Button", label: "Button" },
  { key: "ButtonGroup", label: "Button Group" },
  { key: "Calendar", label: "Calendar" },
  { key: "Card", label: "Card" },
  { key: "Checkbox", label: "Checkbox" },
  { key: "CheckboxCard", label: "Checkbox Card" },
  { key: "CheckboxGroup", label: "Checkbox Group" },
  { key: "Code", label: "Code" },
  { key: "CodeBlock", label: "Code Block" },
  { key: "Combobox", label: "Combobox" },
  { key: "ContentHeader", label: "ContentHeader", description: "Includes buttons & links" },
  { key: "DataTable", label: "Data Table" },
  { key: "DateField", label: "Date Field" },
  { key: "DatePicker", label: "Date Picker" },
  { key: "DescriptionList", label: "Description List" },
  { key: "Divider", label: "Divider" },
  { key: "DividerVertical", label: "Divider" },
  { key: "EmptyState", label: "Empty State" },
  { key: "FileDrop", label: "File Drop" },
  { key: "Form", label: "Form" },
  { key: "FormControl", label: "Form Control" },
  { key: "IconButton", label: "Icon Button" },
  { key: "Link", label: "Link" },
  { key: "Mark", label: "Mark" },
  { key: "NavList", label: "Nav List" },
  { key: "OrderedList", label: "Ordered List" },
  { key: "Pagination", label: "Pagination" },
  { key: "RadioCard", label: "Radio Card" },
  { key: "RadioGroup", label: "Radio Group" },
  { key: "RangeCalendar", label: "Range Calendar" },
  { key: "RangeDateField", label: "Range Date Field" },
  { key: "RangeDatePicker", label: "Range Date Picker" },
  { key: "RangeTimeField", label: "Range Time Field" },
  { key: "RangeTimePicker", label: "Range Time Picker" },
  { key: "Search", label: "Search" },
  { key: "SegmentedControl", label: "Segmented Control" },
  { key: "Select", label: "Select" },
  { key: "StatusLabel", label: "Status Label" },
  { key: "Stepper", label: "Stepper" },
  { key: "Switch", label: "Switch" },
  { key: "Tabs", label: "Tabs" },
  { key: "Tag", label: "Tag" },
  { key: "TagGroup", label: "Tag Group" },
  { key: "TagInput", label: "Tag Input" },
  { key: "TagPicker", label: "Tag Picker" },
  { key: "Text", label: "Text" },
  { key: "TextField", label: "Text Field" },
  { key: "Textarea", label: "Textarea" },
  { key: "TimeField", label: "Time Field" },
  { key: "TimePicker", label: "Time Picker" },
  { key: "Timeline", label: "Timeline" },
  { key: "Toolbar", label: "Toolbar" },
  { key: "Tree", label: "Tree" },
  { key: "UnorderedList", label: "Unordered List" },
  { key: "SideNavigation", label: "Side Navigation" },
];

// --- Shared component key sets ---

const HEADER_COMPONENTS: ComponentKey[] = [
  "Button",
  "ButtonGroup",
  "ContentHeader",
  "DividerVertical",
  "IconButton",
  "Link",
  "Text",
];

const FOOTER_COMPONENTS: ComponentKey[] = ["Button", "ButtonGroup", "DividerVertical", "IconButton", "Link", "Text"];

const GLOBAL_HEADER_COMPONENTS: ComponentKey[] = [
  "Avatar",
  "Button",
  "ButtonGroup",
  "DividerVertical",
  "IconButton",
  "Link",
  "Search",
  "SegmentedControl",
  "StatusLabel",
  "Text",
];

const BASE_BODY: ComponentKey[] = [
  "Accordion",
  "ActionList",
  "Avatar",
  "AvatarGroup",
  "Banner",
  "Blockquote",
  "Breadcrumb",
  "Button",
  "ButtonGroup",
  "Calendar",
  "Card",
  "Checkbox",
  "CheckboxCard",
  "CheckboxGroup",
  "Code",
  "CodeBlock",
  "Combobox",
  "ContentHeader",
  "DataTable",
  "DateField",
  "DatePicker",
  "DescriptionList",
  "Divider",
  "EmptyState",
  "FileDrop",
  "Form",
  "FormControl",
  "IconButton",
  "Link",
  "Mark",
  "OrderedList",
  "RadioCard",
  "RadioGroup",
  "RangeCalendar",
  "RangeDateField",
  "RangeDatePicker",
  "RangeTimeField",
  "RangeTimePicker",
  "Search",
  "SegmentedControl",
  "Select",
  "StatusLabel",
  "Stepper",
  "Switch",
  "Tabs",
  "Tag",
  "TagGroup",
  "TagInput",
  "TagPicker",
  "Text",
  "TextField",
  "Textarea",
  "TimeField",
  "TimePicker",
  "Timeline",
  "Toolbar",
  "UnorderedList",
];

// SidebarStart(outside) body のみ NavList を含む
const SIDEBAR_START_BODY: ComponentKey[] = [
  "Accordion",
  "ActionList",
  "Avatar",
  "AvatarGroup",
  "Banner",
  "Blockquote",
  "Breadcrumb",
  "Button",
  "ButtonGroup",
  "Calendar",
  "Card",
  "Checkbox",
  "CheckboxCard",
  "CheckboxGroup",
  "Code",
  "CodeBlock",
  "Combobox",
  "ContentHeader",
  "DataTable",
  "DateField",
  "DatePicker",
  "DescriptionList",
  "Divider",
  "EmptyState",
  "FileDrop",
  "Form",
  "FormControl",
  "IconButton",
  "Link",
  "Mark",
  "NavList",
  "OrderedList",
  "RadioCard",
  "RadioGroup",
  "RangeCalendar",
  "RangeDateField",
  "RangeDatePicker",
  "RangeTimeField",
  "RangeTimePicker",
  "Search",
  "SegmentedControl",
  "Select",
  "StatusLabel",
  "Stepper",
  "Switch",
  "Tabs",
  "Tag",
  "TagGroup",
  "TagInput",
  "TagPicker",
  "Text",
  "TextField",
  "Textarea",
  "TimeField",
  "TimePicker",
  "Timeline",
  "Toolbar",
  "UnorderedList",
];

const CONTENT_BODY: ComponentKey[] = [
  "Accordion",
  "ActionList",
  "Avatar",
  "AvatarGroup",
  "Banner",
  "Blockquote",
  "Breadcrumb",
  "Button",
  "ButtonGroup",
  "Calendar",
  "Card",
  "Checkbox",
  "CheckboxCard",
  "CheckboxGroup",
  "Code",
  "CodeBlock",
  "Combobox",
  "ContentHeader",
  "DataTable",
  "DateField",
  "DatePicker",
  "DescriptionList",
  "Divider",
  "EmptyState",
  "FileDrop",
  "Form",
  "FormControl",
  "IconButton",
  "Link",
  "Mark",
  "OrderedList",
  "RadioCard",
  "RadioGroup",
  "RangeCalendar",
  "RangeDateField",
  "RangeDatePicker",
  "RangeTimeField",
  "RangeTimePicker",
  "Search",
  "SegmentedControl",
  "Select",
  "StatusLabel",
  "Stepper",
  "Switch",
  "Tabs",
  "Tag",
  "TagGroup",
  "TagInput",
  "TagPicker",
  "Text",
  "TextField",
  "Textarea",
  "TimeField",
  "TimePicker",
  "Timeline",
  "Toolbar",
  "Tree",
  "UnorderedList",
];

const PANE_START_BODY: ComponentKey[] = [
  "IconButton",
  "Link",
  "Mark",
  "NavList",
  "OrderedList",
  "RadioCard",
  "RadioGroup",
  "RangeCalendar",
  "RangeDateField",
  "RangeDatePicker",
  "RangeTimeField",
  "RangeTimePicker",
  "Search",
  "SegmentedControl",
  "Select",
  "StatusLabel",
  "Stepper",
  "Switch",
  "Tabs",
  "Tag",
  "TagGroup",
  "TagInput",
  "TagPicker",
  "Text",
  "TextField",
  "Textarea",
  "TimeField",
  "TimePicker",
  "Timeline",
  "Toolbar",
  "Tree",
  "UnorderedList",
];

// --- Area registry ---

const AREA_REGISTRY: Record<ContentArea, ComponentKey[]> = {
  globalHeader: GLOBAL_HEADER_COMPONENTS,
  globalFooter: FOOTER_COMPONENTS,
  contentHeader: HEADER_COMPONENTS,
  contentBody: CONTENT_BODY,
  contentFooter: FOOTER_COMPONENTS,
  paneStartHeader: HEADER_COMPONENTS,
  paneStartBody: PANE_START_BODY,
  paneStartFooter: FOOTER_COMPONENTS,
  paneEndHeader: HEADER_COMPONENTS,
  paneEndBody: BASE_BODY,
  paneEndFooter: FOOTER_COMPONENTS,
  outerSidebarStartHeader: HEADER_COMPONENTS,
  outerSidebarStartBody: SIDEBAR_START_BODY,
  outerSidebarStartFooter: FOOTER_COMPONENTS,
  outerSidebarEndHeader: HEADER_COMPONENTS,
  outerSidebarEndBody: BASE_BODY,
  outerSidebarEndFooter: FOOTER_COMPONENTS,
  innerSidebarStart: ["SideNavigation"],
  innerSidebarEnd: ["SideNavigation"],
};

export const getAreaRegistry = (area: ContentArea): { key: ComponentKey; label: string; description?: string }[] => {
  const keys = AREA_REGISTRY[area];
  return COMPONENT_REGISTRY.filter(({ key }) => keys.includes(key));
};

export const AREA_COMPONENT_DEFAULT_PROPS: Partial<
  Record<ContentArea, Partial<Record<ComponentKey, Record<string, string>>>>
> = {
  contentBody: { Banner: { size: "medium" } },
  outerSidebarStartBody: { Banner: { size: "small" } },
  outerSidebarEndBody: { Banner: { size: "small" } },
  paneStartBody: { Banner: { size: "small" } },
  paneEndBody: { Banner: { size: "small" } },
};
