import type { FieldConfig } from "./base";
import { SIZE_S_M_L } from "./base";

const LT_TYPES = ["Icon", "Badge", "Tag", "StatusLabel"];
const BADGE_COLORS = ["neutral", "subtle", "success", "information", "warning", "danger", "inverse"];
const TAG_COLORS = [
  "neutral",
  "transparent",
  "red",
  "orange",
  "yellow",
  "lime",
  "teal",
  "blue",
  "indigo",
  "purple",
  "magenta",
  "inverse",
];
const SL_COLORS = ["neutral", "red", "yellow", "blue", "teal", "gray"];
const STYLE_OPT = ["outline", "fill"];

/** スロット (leading1 等) に対して Icon/Badge/Tag/StatusLabel の設定フィールド群を生成するヘルパー */
const ltFields = (
  slot: string,
  slotLabel: string,
  enabledWhen: (p: Record<string, string>) => boolean,
): FieldConfig[] => [
  {
    key: `${slot}Type`,
    label: slotLabel,
    type: "select",
    options: LT_TYPES,
    defaultValue: "Icon",
    visibleWhen: enabledWhen,
    tab: "Content",
  },
  // Icon
  {
    key: `${slot}Icon`,
    label: `${slotLabel} Icon`,
    type: "icon-combobox",
    indent: true,
    visibleWhen: (p) => enabledWhen(p) && (p[`${slot}Type`] ?? "Icon") === "Icon",
    tab: "Content",
  },
  // Badge
  {
    key: `${slot}BadgeColor`,
    label: "Badge Color",
    type: "select",
    options: BADGE_COLORS,
    defaultValue: "neutral",
    indent: true,
    visibleWhen: (p) => enabledWhen(p) && p[`${slot}Type`] === "Badge",
    tab: "Content",
  },
  {
    key: `${slot}BadgeType`,
    label: "Badge Type",
    type: "select",
    options: ["Normal", "Count"],
    defaultValue: "Normal",
    indent: true,
    visibleWhen: (p) => enabledWhen(p) && p[`${slot}Type`] === "Badge",
    tab: "Content",
  },
  {
    key: `${slot}BadgeCountLabel`,
    label: "Count Label",
    type: "textarea",
    placeholder: "0,1,1000",
    defaultValue: "0,1,2,3,4,5,6,7,8,9,1000",
    multiValue: true,
    indent: true,
    visibleWhen: (p) => enabledWhen(p) && p[`${slot}Type`] === "Badge" && p[`${slot}BadgeType`] === "Count",
    tab: "Content",
  },
  // Tag
  {
    key: `${slot}TagStyle`,
    label: "Tag Variant",
    type: "select",
    options: STYLE_OPT,
    defaultValue: "outline",
    indent: true,
    visibleWhen: (p) => enabledWhen(p) && p[`${slot}Type`] === "Tag",
    tab: "Content",
  },
  {
    key: `${slot}TagColor`,
    label: "Tag Color",
    type: "select",
    options: TAG_COLORS,
    defaultValue: "neutral",
    indent: true,
    visibleWhen: (p) => enabledWhen(p) && p[`${slot}Type`] === "Tag",
    tab: "Content",
  },
  {
    key: `${slot}TagLabel`,
    label: "Tag Label",
    type: "textarea",
    placeholder: "AAA,BBB,CCC",
    multiValue: true,
    indent: true,
    visibleWhen: (p) => enabledWhen(p) && p[`${slot}Type`] === "Tag",
    tab: "Content",
  },
  // StatusLabel
  {
    key: `${slot}StatusStyle`,
    label: "StatusLabel Variant",
    type: "select",
    options: STYLE_OPT,
    defaultValue: "outline",
    indent: true,
    visibleWhen: (p) => enabledWhen(p) && p[`${slot}Type`] === "StatusLabel",
    tab: "Content",
  },
  {
    key: `${slot}StatusColor`,
    label: "StatusLabel Color",
    type: "select",
    options: SL_COLORS,
    defaultValue: "gray",
    indent: true,
    visibleWhen: (p) => enabledWhen(p) && p[`${slot}Type`] === "StatusLabel",
    tab: "Content",
  },
  {
    key: `${slot}StatusLabel`,
    label: "StatusLabel Label",
    type: "textarea",
    placeholder: "AAA,BBB,CCC",
    multiValue: true,
    indent: true,
    visibleWhen: (p) => enabledWhen(p) && p[`${slot}Type`] === "StatusLabel",
    tab: "Content",
  },
];

export const ActionListConfig: FieldConfig[] = [
  // --- Properties ---
  { ...SIZE_S_M_L, tab: "Properties" },
  { key: "selectionType", label: "Selection Type", type: "checkbox", tab: "Properties" },
  { key: "leading1", label: "Leading-1", type: "checkbox", tab: "Properties" },
  {
    key: "leading2",
    label: "Leading-2",
    type: "checkbox",
    disabledWhen: (p) => p.leading1 !== "true",
    tab: "Properties",
  },
  { key: "trailing1", label: "Trailing-1", type: "checkbox", tab: "Properties" },
  {
    key: "trailing2",
    label: "Trailing-2",
    type: "checkbox",
    disabledWhen: (p) => p.trailing1 !== "true",
    tab: "Properties",
  },
  { key: "avatar", label: "Avatar", type: "checkbox", tab: "Properties" },
  { key: "trailingButton", label: "Trailing Button", type: "checkbox", tab: "Properties" },
  { key: "withGroup", label: "With Group", type: "checkbox", tab: "Properties" },
  { key: "withGroupTitle", label: "With Group Title", type: "checkbox", tab: "Properties" },
  { key: "withDescription", label: "With Description", type: "checkbox", tab: "Properties" },

  // --- Content ---
  ...ltFields("leading1", "Leading-1", (p) => p.leading1 === "true"),
  ...ltFields("leading2", "Leading-2", (p) => p.leading2 === "true"),
  ...ltFields("trailing1", "Trailing-1", (p) => p.trailing1 === "true"),
  ...ltFields("trailing2", "Trailing-2", (p) => p.trailing2 === "true"),

  // Trailing Button
  {
    key: "buttonLabel",
    label: "Button Label",
    type: "textarea",
    placeholder: "AAA,BBB,CCC",
    multiValue: true,
    visibleWhen: (p) => p.trailingButton === "true",
    tab: "Content",
  },
  {
    key: "buttonColor",
    label: "Button Color",
    type: "select",
    options: ["solid", "subtle", "plain"],
    defaultValue: "plain",
    visibleWhen: (p) => p.trailingButton === "true",
    tab: "Content",
  },

  // Items
  {
    key: "items",
    label: "Items",
    type: "stepper",
    min: 1,
    max: 20,
    defaultValue: "3",
    visibleWhen: (p) => p.withGroup !== "true",
    tab: "Content",
  },
  {
    key: "groups",
    label: "Groups",
    type: "stepper",
    min: 2,
    max: 5,
    defaultValue: "2",
    visibleWhen: (p) => p.withGroup === "true",
    tab: "Content",
  },
  {
    key: "items1",
    label: "Items (Group-1)",
    type: "stepper",
    min: 1,
    max: 20,
    defaultValue: "3",
    indent: true,
    visibleWhen: (p) => p.withGroup === "true",
    tab: "Content",
  },
  {
    key: "items2",
    label: "Items (Group-2)",
    type: "stepper",
    min: 1,
    max: 20,
    defaultValue: "3",
    indent: true,
    visibleWhen: (p) => p.withGroup === "true",
    tab: "Content",
  },
  {
    key: "items3",
    label: "Items (Group-3)",
    type: "stepper",
    min: 1,
    max: 20,
    defaultValue: "3",
    indent: true,
    visibleWhen: (p) => p.withGroup === "true" && parseInt(p.groups ?? "2", 10) >= 3,
    tab: "Content",
  },
  {
    key: "items4",
    label: "Items (Group-4)",
    type: "stepper",
    min: 1,
    max: 20,
    defaultValue: "3",
    indent: true,
    visibleWhen: (p) => p.withGroup === "true" && parseInt(p.groups ?? "2", 10) >= 4,
    tab: "Content",
  },
  {
    key: "items5",
    label: "Items (Group-5)",
    type: "stepper",
    min: 1,
    max: 20,
    defaultValue: "3",
    indent: true,
    visibleWhen: (p) => p.withGroup === "true" && parseInt(p.groups ?? "2", 10) >= 5,
    tab: "Content",
  },

  // Labels & Descriptions
  { key: "listLabel", label: "Label", type: "textarea", placeholder: "AAA,BBB,CCC", multiValue: true, tab: "Content" },
  {
    key: "description",
    label: "Description",
    type: "textarea",
    placeholder: "AAA,BBB,CCC",
    multiValue: true,
    visibleWhen: (p) => p.withDescription === "true",
    tab: "Content",
  },
];
