import type { FieldConfig } from "./base";

export const ButtonGroupConfig: FieldConfig[] = [
  // --- Properties ---
  {
    key: "size",
    label: "Size",
    type: "select",
    options: ["large", "medium", "small", "xSmall"],
    defaultValue: "medium",
    tab: "Properties",
  },
  { key: "attached", label: "Attached", type: "checkbox", tab: "Properties" },
  {
    key: "attachedColor",
    label: "Attached Color",
    type: "select",
    options: ["solid", "subtle", "plain"],
    defaultValue: "solid",
    indent: true,
    visibleWhen: (p) => p.attached === "true",
    tab: "Properties",
  },

  // --- Content ---

  // Button Items
  {
    key: "btnItems",
    label: "Button Items",
    type: "stepper",
    min: 0,
    max: 5,
    defaultValue: "3",
    tab: "Content",
    minGetter: (p) => Math.max(0, 2 - parseInt(p.iconItems ?? "1", 10)),
  },
  {
    key: "btn1",
    label: "Item-1",
    type: "button",
    subComponent: "Button",
    excludedSubKeys: ["size"],
    indent: true,
    visibleWhen: (p) => parseInt(p.btnItems ?? "3", 10) >= 1,
    tab: "Content",
  },
  {
    key: "btn2",
    label: "Item-2",
    type: "button",
    subComponent: "Button",
    excludedSubKeys: ["size"],
    indent: true,
    visibleWhen: (p) => parseInt(p.btnItems ?? "3", 10) >= 2,
    tab: "Content",
  },
  {
    key: "btn3",
    label: "Item-3",
    type: "button",
    subComponent: "Button",
    excludedSubKeys: ["size"],
    indent: true,
    visibleWhen: (p) => parseInt(p.btnItems ?? "3", 10) >= 3,
    tab: "Content",
  },
  {
    key: "btn4",
    label: "Item-4",
    type: "button",
    subComponent: "Button",
    excludedSubKeys: ["size"],
    indent: true,
    visibleWhen: (p) => parseInt(p.btnItems ?? "3", 10) >= 4,
    tab: "Content",
  },
  {
    key: "btn5",
    label: "Item-5",
    type: "button",
    subComponent: "Button",
    excludedSubKeys: ["size"],
    indent: true,
    visibleWhen: (p) => parseInt(p.btnItems ?? "3", 10) >= 5,
    tab: "Content",
  },

  // IconButton Items
  {
    key: "iconItems",
    label: "IconButton Items",
    type: "stepper",
    min: 0,
    max: 5,
    defaultValue: "1",
    tab: "Content",
    minGetter: (p) => Math.max(0, 2 - parseInt(p.btnItems ?? "3", 10)),
  },
  {
    key: "icon1",
    label: "Item-1",
    type: "button",
    subComponent: "IconButton",
    excludedSubKeys: ["size"],
    indent: true,
    visibleWhen: (p) => parseInt(p.iconItems ?? "1", 10) >= 1,
    tab: "Content",
  },
  {
    key: "icon2",
    label: "Item-2",
    type: "button",
    subComponent: "IconButton",
    excludedSubKeys: ["size"],
    indent: true,
    visibleWhen: (p) => parseInt(p.iconItems ?? "1", 10) >= 2,
    tab: "Content",
  },
  {
    key: "icon3",
    label: "Item-3",
    type: "button",
    subComponent: "IconButton",
    excludedSubKeys: ["size"],
    indent: true,
    visibleWhen: (p) => parseInt(p.iconItems ?? "1", 10) >= 3,
    tab: "Content",
  },
  {
    key: "icon4",
    label: "Item-4",
    type: "button",
    subComponent: "IconButton",
    excludedSubKeys: ["size"],
    indent: true,
    visibleWhen: (p) => parseInt(p.iconItems ?? "1", 10) >= 4,
    tab: "Content",
  },
  {
    key: "icon5",
    label: "Item-5",
    type: "button",
    subComponent: "IconButton",
    excludedSubKeys: ["size"],
    indent: true,
    visibleWhen: (p) => parseInt(p.iconItems ?? "1", 10) >= 5,
    tab: "Content",
  },
];
