import type { FieldConfig } from "./base";

export const CardConfig: FieldConfig[] = [
  // --- Properties ---
  {
    key: "size",
    label: "Size",
    type: "select",
    options: ["medium", "small", "xSmall"],
    defaultValue: "medium",
    tab: "Properties",
  },
  {
    key: "variant",
    label: "Variant",
    type: "select",
    options: ["outline", "fill", "plain"],
    defaultValue: "outline",
    tab: "Properties",
  },
  { key: "header", label: "Header", type: "checkbox", defaultValue: "true", tab: "Properties" },
  {
    key: "withHeaderLeading",
    label: "With Header Leading",
    type: "checkbox",
    indent: true,
    visibleWhen: (p) => p.header !== "false",
    tab: "Properties",
  },
  {
    key: "withHeaderTrailing",
    label: "With Header Trailing",
    type: "checkbox",
    indent: true,
    visibleWhen: (p) => p.header !== "false",
    tab: "Properties",
  },
  { key: "body", label: "Body", type: "checkbox", defaultValue: "true", tab: "Properties" },
  { key: "footer", label: "Footer", type: "checkbox", tab: "Properties" },
  { key: "clickAction", label: "Click Action", type: "checkbox", tab: "Properties" },
  {
    key: "actionType",
    label: "Action Type",
    type: "select",
    options: ["With Link", "Link As Button"],
    defaultValue: "With Link",
    tab: "Properties",
    indent: true,
    visibleWhen: (p) => p.clickAction === "true",
  },
  {
    key: "linkAsToggleButton",
    label: "Link As Toggle Button",
    type: "checkbox",
    indent: true,
    visibleWhen: (p) => p.clickAction === "true",
    disabledWhen: (p) => (p.actionType ?? "With Link") !== "Link As Button",
    tab: "Properties",
  },
  { key: "nestedCard", label: "Nested Card With Card Link Button", type: "checkbox", tab: "Properties" },
  { key: "withinGrid", label: "Within Grid", type: "checkbox", tab: "Properties" },

  // --- Content ---
  // Header (visible when Header = On)
  {
    key: "headerText",
    label: "Header Text",
    type: "textfield",
    defaultValue: "Card Title",
    tab: "Content",
    visibleWhen: (p) => p.header !== "false",
  },
  {
    key: "headerTypo",
    label: "Header Style",
    type: "typography-select",
    subComponent: "Text",
    allowedTextTypes: ["title", "body"],
    tab: "Content",
    visibleWhen: (p) => p.header !== "false",
  },

  // Leading (visible when Header = On AND With Header Leading = On)
  {
    key: "leadingType",
    label: "Leading Type",
    type: "select",
    options: ["Icon", "IconButton", "StatusLabel", "Tag"],
    defaultValue: "Icon",
    tab: "Content",
    visibleWhen: (p) => p.header !== "false" && p.withHeaderLeading === "true",
  },
  {
    key: "leadingIBtn",
    label: "Leading IconButton",
    type: "button",
    subComponent: "IconButton",
    indent: true,
    tab: "Content",
    visibleWhen: (p) => p.header !== "false" && p.withHeaderLeading === "true" && p.leadingType === "IconButton",
    excludedSubKeys: ["size"],
  },
  {
    key: "leadingIcon",
    label: "Leading Icon",
    type: "icon-combobox",
    defaultValue: "LfPlusLarge",
    indent: true,
    tab: "Content",
    visibleWhen: (p) => p.header !== "false" && p.withHeaderLeading === "true" && (p.leadingType ?? "Icon") === "Icon",
  },
  {
    key: "leadingStatus",
    label: "Leading StatusLabel",
    type: "button",
    subComponent: "StatusLabel",
    indent: true,
    tab: "Content",
    visibleWhen: (p) => p.header !== "false" && p.withHeaderLeading === "true" && p.leadingType === "StatusLabel",
  },
  {
    key: "leadingTag",
    label: "Leading Tag",
    type: "button",
    subComponent: "Tag",
    indent: true,
    tab: "Content",
    visibleWhen: (p) => p.header !== "false" && p.withHeaderLeading === "true" && p.leadingType === "Tag",
  },

  // Trailing (visible when Header = On AND With Header Trailing = On)
  {
    key: "trailingType",
    label: "Trailing Type",
    type: "select",
    options: ["Icon", "IconButton", "StatusLabel", "Tag"],
    defaultValue: "Icon",
    tab: "Content",
    visibleWhen: (p) => p.header !== "false" && p.withHeaderTrailing === "true",
  },
  {
    key: "trailingIBtn",
    label: "Trailing IconButton",
    type: "button",
    subComponent: "IconButton",
    indent: true,
    tab: "Content",
    visibleWhen: (p) => p.header !== "false" && p.withHeaderTrailing === "true" && p.trailingType === "IconButton",
    excludedSubKeys: ["size"],
  },
  {
    key: "trailingIcon",
    label: "Trailing Icon",
    type: "icon-combobox",
    defaultValue: "LfPlusLarge",
    indent: true,
    tab: "Content",
    visibleWhen: (p) =>
      p.header !== "false" && p.withHeaderTrailing === "true" && (p.trailingType ?? "Icon") === "Icon",
  },
  {
    key: "trailingStatus",
    label: "Trailing StatusLabel",
    type: "button",
    subComponent: "StatusLabel",
    indent: true,
    tab: "Content",
    visibleWhen: (p) => p.header !== "false" && p.withHeaderTrailing === "true" && p.trailingType === "StatusLabel",
  },
  {
    key: "trailingTag",
    label: "Trailing Tag",
    type: "button",
    subComponent: "Tag",
    indent: true,
    tab: "Content",
    visibleWhen: (p) => p.header !== "false" && p.withHeaderTrailing === "true" && p.trailingType === "Tag",
  },

  // Body (visible when Body = On)
  {
    key: "_dividerBody",
    label: "",
    type: "divider",
    tab: "Content",
    visibleWhen: (p) => p.header !== "false" && p.body !== "false",
  },
  {
    key: "bodyText",
    label: "Body Text",
    type: "textarea",
    defaultValue: "Card content goes here.",
    tab: "Content",
    visibleWhen: (p) => p.body !== "false",
  },
  {
    key: "bodyTypo",
    label: "Body Style",
    type: "typography-select",
    subComponent: "Text",
    allowedTextTypes: ["body"],
    tab: "Content",
    visibleWhen: (p) => p.body !== "false",
  },

  // Footer (visible when Footer = On)
  {
    key: "_dividerFooter",
    label: "",
    type: "divider",
    tab: "Content",
    visibleWhen: (p) => p.footer === "true" && (p.body !== "false" || p.header !== "false"),
  },
  {
    key: "contentType",
    label: "Footer Content Type",
    type: "select",
    options: ["Button", "IconButton", "ButtonGroup"],
    defaultValue: "Button",
    tab: "Content",
    visibleWhen: (p) => p.footer === "true",
  },
  {
    key: "footerContentBtn",
    label: "Footer Content",
    type: "button",
    subComponent: "Button",
    tab: "Content",
    visibleWhen: (p) => p.footer === "true" && (p.contentType ?? "Button") === "Button",
  },
  {
    key: "footerContentIBtn",
    label: "Footer Content",
    type: "button",
    subComponent: "IconButton",
    tab: "Content",
    visibleWhen: (p) => p.footer === "true" && p.contentType === "IconButton",
  },
  {
    key: "footerContentBtnGrp",
    label: "Footer Content",
    type: "button",
    subComponent: "ButtonGroup",
    tab: "Content",
    visibleWhen: (p) => p.footer === "true" && p.contentType === "ButtonGroup",
  },
];
