import type { FieldConfig } from "./base";

const fcGroupInputOptions = [
  "TextField",
  "Select",
  "Combobox",
  "DatePicker",
  "DateField",
  "TagPicker",
  "TagInput",
  "RangeDatePicker",
  "TimePicker",
  "TimeField",
];

export const DateFieldConfig: FieldConfig[] = [
  // --- Properties ---
  {
    key: "size",
    label: "Size",
    type: "select",
    options: ["large", "medium"],
    defaultValue: "medium",
    tab: "Properties",
  },
  { key: "granularity", label: "Granularity (minute)", type: "checkbox", tab: "Properties" },
  { key: "leading", label: "Leading", type: "checkbox", tab: "Properties" },
  { key: "trailing", label: "Trailing", type: "checkbox", tab: "Properties" },
  { key: "_dividerWFC", label: "", type: "divider", tab: "Properties" },
  { key: "withinFormControl", label: "Within Form Control", type: "checkbox", defaultValue: "true", tab: "Properties" },
  {
    key: "orientation",
    label: "Orientation",
    type: "select",
    options: ["vertical", "horizontal"],
    defaultValue: "vertical",
    visibleWhen: (p) => p.withinFormControl !== "false",
    tab: "Properties",
  },
  {
    key: "fcTitle",
    label: "FormControl Title",
    type: "checkbox",
    defaultValue: "true",
    visibleWhen: (p) => p.withinFormControl !== "false",
    tab: "Properties",
  },

  // visible when Within Form Control is On
  {
    key: "required",
    label: "Required",
    type: "checkbox",
    indent: true,
    indentParentKey: "fcTitle",
    visibleWhen: (p) => p.withinFormControl !== "false" && p.fcTitle !== "false",
    tab: "Properties",
  },
  {
    key: "labelWidth",
    label: "Label Width",
    type: "select",
    options: ["Off", "xSmall", "small", "medium", "auto"],
    defaultValue: "Off",
    indent: true,
    visibleWhen: (p) => p.withinFormControl !== "false" && (p.orientation ?? "vertical") !== "vertical",
    tab: "Properties",
  },
  {
    key: "labelWeight",
    label: "Label Weight",
    type: "select",
    options: ["bold", "normal"],
    defaultValue: "bold",
    indent: true,
    visibleWhen: (p) => p.withinFormControl !== "false" && (p.orientation ?? "vertical") !== "vertical",
    tab: "Properties",
  },
  {
    key: "labelTrailing",
    label: "Label Trailing",
    type: "checkbox",
    indent: true,
    visibleWhen: (p) => p.withinFormControl !== "false" && (p.orientation ?? "vertical") !== "vertical",
    tab: "Properties",
  },
  {
    key: "fcGroup",
    label: "With Group",
    type: "checkbox",
    visibleWhen: (p) => p.withinFormControl !== "false",
    tab: "Properties",
  },
  {
    key: "fcGroupInputType",
    label: "Input Type",
    type: "select",
    options: fcGroupInputOptions,
    defaultValue: "Select",
    indent: true,
    visibleWhen: (p) => p.withinFormControl !== "false" && p.fcGroup === "true",
    tab: "Properties",
  },
  {
    key: "withToolbar",
    label: "With Toolbar",
    type: "checkbox",
    visibleWhen: (p) => p.withinFormControl !== "false",
    tab: "Properties",
  },
  {
    key: "withGhostToolbar",
    label: "With Ghost Toolbar",
    type: "checkbox",
    indent: true,
    visibleWhen: (p) => p.withinFormControl !== "false" && p.withToolbar === "true",
    tab: "Properties",
  },
  {
    key: "fcCaption",
    label: "FormControl Caption",
    type: "checkbox",
    defaultValue: "false",
    visibleWhen: (p) => p.withinFormControl !== "false",
    tab: "Properties",
  },

  // --- Content ---
  {
    key: "fcLabel",
    label: "FormControl Label",
    type: "textfield",
    defaultValue: "Label",
    tab: "Content",
    visibleWhen: (p) => p.withinFormControl !== "false" && p.fcTitle !== "false",
  },
  {
    key: "toolbarItems",
    label: "With Toolbar Items",
    type: "stepper",
    min: 1,
    max: 3,
    defaultValue: "2",
    tab: "Content",
    visibleWhen: (p) => p.withinFormControl !== "false" && p.withToolbar === "true",
  },
  {
    key: "btnLabel",
    label: "ButtonLabel",
    type: "textfield",
    indent: true,
    defaultValue: "Action",
    tab: "Content",
    visibleWhen: (p) =>
      p.withinFormControl !== "false" && p.withToolbar === "true" && parseInt(p.toolbarItems ?? "2", 10) === 1,
  },
  {
    key: "btnLabel1",
    label: "ButtonLabel-1",
    type: "textfield",
    indent: true,
    defaultValue: "Action 1",
    tab: "Content",
    visibleWhen: (p) =>
      p.withinFormControl !== "false" && p.withToolbar === "true" && parseInt(p.toolbarItems ?? "2", 10) >= 2,
  },
  {
    key: "btnLabel2",
    label: "ButtonLabel-2",
    type: "textfield",
    indent: true,
    defaultValue: "Action 2",
    tab: "Content",
    visibleWhen: (p) =>
      p.withinFormControl !== "false" && p.withToolbar === "true" && parseInt(p.toolbarItems ?? "2", 10) >= 2,
  },
  {
    key: "btnLabel3",
    label: "ButtonLabel-3",
    type: "textfield",
    indent: true,
    defaultValue: "Action 3",
    tab: "Content",
    visibleWhen: (p) =>
      p.withinFormControl !== "false" && p.withToolbar === "true" && parseInt(p.toolbarItems ?? "2", 10) >= 3,
  },
  {
    key: "leadingIcon",
    label: "Leading Icon",
    type: "icon-combobox",
    defaultValue: "LfPlusLarge",
    tab: "Content",
    visibleWhen: (p) => p.leading === "true",
  },
  {
    key: "trailingIcon",
    label: "Trailing Icon",
    type: "icon-combobox",
    defaultValue: "LfPlusLarge",
    tab: "Content",
    visibleWhen: (p) => p.trailing === "true",
  },

  {
    key: "_dividerFcCaption",
    label: "",
    type: "divider",
    tab: "Content",
    visibleWhen: (p) => p.withinFormControl !== "false" && p.fcCaption === "true",
  },
  {
    key: "fcCaptionText",
    label: "FormControl Caption",
    type: "textfield",
    defaultValue: "Caption text",
    tab: "Content",
    visibleWhen: (p) => p.withinFormControl !== "false" && p.fcCaption === "true",
  },
];
