import type { FieldConfig } from "./base";

const INPUT_TYPE_OPTIONS = [
  "Select",
  "Combobox",
  "DateField",
  "DatePicker",
  "RangeDatePicker",
  "Search",
  "TagInput",
  "TagPicker",
  "TextArea",
  "TextField",
  "TimeField",
  "TimePicker",
];

const NO_PLACEHOLDER = ["DateField", "DatePicker", "RangeDatePicker", "TimeField", "TimePicker"];

export const FormControlConfig: FieldConfig[] = [
  // --- Properties ---
  {
    key: "fcOrientation",
    label: "Orientation",
    type: "select",
    options: ["Vertical", "Horizontal"],
    defaultValue: "Vertical",
    tab: "Properties",
  },
  {
    key: "inputType1",
    label: "Input Type",
    type: "select",
    options: INPUT_TYPE_OPTIONS,
    defaultValue: "Select",
    tab: "Properties",
  },
  { key: "_divider1", label: "", type: "divider", tab: "Properties" },
  {
    key: "size",
    label: "Size",
    type: "select",
    options: ["large", "medium", "small"],
    defaultValue: "medium",
    tab: "Properties",
  },
  { key: "leading", label: "Leading", type: "checkbox", tab: "Properties" },
  { key: "trailing", label: "Trailing", type: "checkbox", tab: "Properties" },
  { key: "required", label: "Required", type: "checkbox", tab: "Properties" },
  { key: "fcGroup", label: "With Group", type: "checkbox", tab: "Properties" },
  {
    key: "fcGroupInputType",
    label: "Group Input Type",
    type: "select",
    options: INPUT_TYPE_OPTIONS,
    defaultValue: "Select",
    indent: true,
    visibleWhen: (p) => p.fcGroup === "true",
    tab: "Properties",
  },
  { key: "withToolbar", label: "With Toolbar", type: "checkbox", tab: "Properties" },
  {
    key: "withGhostToolbar",
    label: "With Ghost Toolbar",
    type: "checkbox",
    indent: true,
    visibleWhen: (p) => p.withToolbar === "true",
    tab: "Properties",
  },
  { key: "fcCaption", label: "FormControl Caption", type: "checkbox", defaultValue: "false", tab: "Properties" },
  {
    key: "fcCaptionText",
    label: "FormControl Caption",
    type: "textfield",
    defaultValue: "Caption text",
    indent: true,
    visibleWhen: (p) => p.fcCaption === "true",
    tab: "Properties",
  },

  // --- Content ---
  { key: "fcLabel", label: "FormControl Label", type: "textfield", defaultValue: "Label", tab: "Content" },
  {
    key: "toolbarItems",
    label: "Toolbar Items",
    type: "stepper",
    min: 1,
    max: 3,
    defaultValue: "2",
    tab: "Content",
    visibleWhen: (p) => p.withToolbar === "true",
  },
  {
    key: "btnLabel",
    label: "ButtonLabel",
    type: "textfield",
    indent: true,
    defaultValue: "Action",
    tab: "Content",
    visibleWhen: (p) => p.withToolbar === "true" && parseInt(p.toolbarItems ?? "2", 10) === 1,
  },
  {
    key: "btnLabel1",
    label: "ButtonLabel-1",
    type: "textfield",
    indent: true,
    defaultValue: "Action 1",
    tab: "Content",
    visibleWhen: (p) => p.withToolbar === "true" && parseInt(p.toolbarItems ?? "2", 10) >= 2,
  },
  {
    key: "btnLabel2",
    label: "ButtonLabel-2",
    type: "textfield",
    indent: true,
    defaultValue: "Action 2",
    tab: "Content",
    visibleWhen: (p) => p.withToolbar === "true" && parseInt(p.toolbarItems ?? "2", 10) >= 2,
  },
  {
    key: "btnLabel3",
    label: "ButtonLabel-3",
    type: "textfield",
    indent: true,
    defaultValue: "Action 3",
    tab: "Content",
    visibleWhen: (p) => p.withToolbar === "true" && parseInt(p.toolbarItems ?? "2", 10) >= 3,
  },
  {
    key: "leadingIcon",
    label: "Leading Icon",
    type: "icon-combobox",
    defaultValue: "LfPlusLarge",
    tab: "Content",
    visibleWhen: (p) => p.leading === "true",
  },
  {
    key: "trailingIcon",
    label: "Trailing Icon",
    type: "icon-combobox",
    defaultValue: "LfPlusLarge",
    tab: "Content",
    visibleWhen: (p) => p.trailing === "true",
  },
  { key: "_dividerContent", label: "", type: "divider", tab: "Content" },
  {
    key: "placeholder",
    label: "Placeholder",
    type: "textfield",
    placeholder: "Placeholder",
    tab: "Content",
    visibleWhen: (p) => !NO_PLACEHOLDER.includes(p.inputType1 ?? "Select"),
  },
  {
    key: "clearable",
    label: "Clearable",
    type: "checkbox",
    tab: "Content",
    visibleWhen: (p) => ["Select", "Combobox"].includes(p.inputType1 ?? "Select"),
  },
  {
    key: "menuItems",
    label: "Options",
    type: "textarea",
    placeholder: "Option A,Option B,Option C",
    defaultValue: "Option A,Option B,Option C",
    tab: "Content",
    visibleWhen: (p) => ["Select", "Combobox"].includes(p.inputType1 ?? "Select"),
  },
  {
    key: "granularity",
    label: "Granularity (minute)",
    type: "checkbox",
    tab: "Content",
    visibleWhen: (p) => ["DateField", "DatePicker"].includes(p.inputType1 ?? "Select"),
  },
  {
    key: "minuteStep",
    label: "Minute Step",
    type: "stepper",
    min: 1,
    max: 60,
    defaultValue: "5",
    tab: "Content",
    visibleWhen: (p) => p.inputType1 === "TimePicker",
  },
];
