import type { FieldConfig } from "./base";

export const TextareaConfig: FieldConfig[] = [
  // --- Properties ---
  { key: "_dividerWFC", label: "", type: "divider", tab: "Properties" },
  { key: "withinFormControl", label: "Within Form Control", type: "checkbox", defaultValue: "true", tab: "Properties" },
  {
    key: "orientation",
    label: "Orientation",
    type: "select",
    options: ["vertical", "horizontal"],
    defaultValue: "vertical",
    visibleWhen: (p) => p.withinFormControl !== "false",
    tab: "Properties",
  },
  {
    key: "fcTitle",
    label: "FormControl Title",
    type: "checkbox",
    defaultValue: "true",
    visibleWhen: (p) => p.withinFormControl !== "false",
    tab: "Properties",
  },

  // visible when Within Form Control is On
  {
    key: "required",
    label: "Required",
    type: "checkbox",
    indent: true,
    indentParentKey: "fcTitle",
    visibleWhen: (p) => p.withinFormControl !== "false" && p.fcTitle !== "false",
    tab: "Properties",
  },
  {
    key: "labelWidth",
    label: "Label Width",
    type: "select",
    options: ["Off", "xSmall", "small", "medium", "auto"],
    defaultValue: "Off",
    indent: true,
    visibleWhen: (p) => p.withinFormControl !== "false" && (p.orientation ?? "vertical") !== "vertical",
    tab: "Properties",
  },
  {
    key: "labelWeight",
    label: "Label Weight",
    type: "select",
    options: ["bold", "normal"],
    defaultValue: "bold",
    indent: true,
    visibleWhen: (p) => p.withinFormControl !== "false" && (p.orientation ?? "vertical") !== "vertical",
    tab: "Properties",
  },
  {
    key: "labelTrailing",
    label: "Label Trailing",
    type: "checkbox",
    indent: true,
    visibleWhen: (p) => p.withinFormControl !== "false" && (p.orientation ?? "vertical") !== "vertical",
    tab: "Properties",
  },
  {
    key: "withToolbar",
    label: "With Toolbar",
    type: "checkbox",
    visibleWhen: (p) => p.withinFormControl !== "false",
    tab: "Properties",
  },
  {
    key: "withGhostToolbar",
    label: "With Ghost Toolbar",
    type: "checkbox",
    indent: true,
    visibleWhen: (p) => p.withinFormControl !== "false" && p.withToolbar === "true",
    tab: "Properties",
  },
  {
    key: "fcCaption",
    label: "FormControl Caption",
    type: "checkbox",
    defaultValue: "false",
    visibleWhen: (p) => p.withinFormControl !== "false",
    tab: "Properties",
  },

  // --- Content ---
  {
    key: "fcLabel",
    label: "FormControl Label",
    type: "textfield",
    defaultValue: "Label",
    tab: "Content",
    visibleWhen: (p) => p.withinFormControl !== "false" && p.fcTitle !== "false",
  },
  {
    key: "toolbarItems",
    label: "With Toolbar Items",
    type: "stepper",
    min: 1,
    max: 3,
    defaultValue: "2",
    tab: "Content",
    visibleWhen: (p) => p.withinFormControl !== "false" && p.withToolbar === "true",
  },
  {
    key: "btnLabel",
    label: "ButtonLabel",
    type: "textfield",
    indent: true,
    defaultValue: "Action",
    tab: "Content",
    visibleWhen: (p) =>
      p.withinFormControl !== "false" && p.withToolbar === "true" && parseInt(p.toolbarItems ?? "2", 10) === 1,
  },
  {
    key: "btnLabel1",
    label: "ButtonLabel-1",
    type: "textfield",
    indent: true,
    defaultValue: "Action 1",
    tab: "Content",
    visibleWhen: (p) =>
      p.withinFormControl !== "false" && p.withToolbar === "true" && parseInt(p.toolbarItems ?? "2", 10) >= 2,
  },
  {
    key: "btnLabel2",
    label: "ButtonLabel-2",
    type: "textfield",
    indent: true,
    defaultValue: "Action 2",
    tab: "Content",
    visibleWhen: (p) =>
      p.withinFormControl !== "false" && p.withToolbar === "true" && parseInt(p.toolbarItems ?? "2", 10) >= 2,
  },
  {
    key: "btnLabel3",
    label: "ButtonLabel-3",
    type: "textfield",
    indent: true,
    defaultValue: "Action 3",
    tab: "Content",
    visibleWhen: (p) =>
      p.withinFormControl !== "false" && p.withToolbar === "true" && parseInt(p.toolbarItems ?? "2", 10) >= 3,
  },
  {
    key: "_dividerFC",
    label: "",
    type: "divider",
    tab: "Content",
    visibleWhen: (p) => p.withinFormControl !== "false",
  },

  { key: "placeholder", label: "Placeholder", type: "textfield", defaultValue: "Placeholder", tab: "Content" },
  { key: "minRows", label: "Min Rows", type: "stepper", min: 1, max: 20, defaultValue: "3", tab: "Content" },
  { key: "hasMaxRows", label: "Max Rows", type: "checkbox", tab: "Content" },
  {
    key: "maxRows",
    label: "Max Rows",
    type: "stepper",
    min: 1,
    max: 20,
    defaultValue: "6",
    indent: true,
    tab: "Content",
    visibleWhen: (p) => p.hasMaxRows === "true",
  },
  { key: "error", label: "Error", type: "checkbox", tab: "Content" },
  { key: "withCountLabel", label: "With Count Label", type: "checkbox", tab: "Content" },
  {
    key: "maxCount",
    label: "Max Count",
    type: "textfield",
    defaultValue: "100",
    indent: true,
    tab: "Content",
    visibleWhen: (p) => p.withCountLabel === "true",
  },

  {
    key: "_dividerFcCaption",
    label: "",
    type: "divider",
    tab: "Content",
    visibleWhen: (p) => p.withinFormControl !== "false" && p.fcCaption === "true",
  },
  {
    key: "fcCaptionText",
    label: "FormControl Caption",
    type: "textfield",
    defaultValue: "Caption text",
    tab: "Content",
    visibleWhen: (p) => p.withinFormControl !== "false" && p.fcCaption === "true",
  },
];
