import type { LocaleCode } from "../../../../../contexts/LocaleContext";
import chartPalette from "./ChartParette.json";
import type { CaseData, CaseType } from "./types";

export const CASE_TYPE_ORDER: CaseType[] = ["契約書審査", "契約書起案", "法務相談", "その他"];

// Case type colors for charts
export const CASE_TYPE_COLORS: Record<string, string> = {
  契約書審査: chartPalette.indigo["900"],
  契約書起案: chartPalette.purple["300"],
  法務相談: chartPalette.red["600(base)"],
  その他: chartPalette.neutral["200"],
};

// ステータス名のマッピング
const STATUS_MAPPING: Record<LocaleCode, Record<string, string>> = {
  "ja-JP": {
    未着手: "未着手",
    確認中: "確認中",
    "2次確認中": "2次確認中",
    自部門外確認中: "自部門外確認中",
    完了: "完了",
  },
  "en-US": {
    未着手: "Not started",
    確認中: "In review",
    "2次確認中": "Secondary review",
    自部門外確認中: "External review",
    完了: "Completed",
  },
};

// ステータス名の逆マッピング（英語→日本語）
const STATUS_REVERSE_MAPPING: Record<string, string> = {
  "Not started": "未着手",
  "In review": "確認中",
  "Secondary review": "2次確認中",
  "External review": "自部門外確認中",
  Completed: "完了",
};

// 案件タイプのマッピング
export const CASE_TYPE_MAPPING: Record<LocaleCode, Record<string, string>> = {
  "ja-JP": {
    契約書審査: "契約書審査",
    契約書起案: "契約書起案",
    法務相談: "法務相談",
    その他: "その他",
  },
  "en-US": {
    契約書審査: "Contract review",
    契約書起案: "Contract drafting",
    法務相談: "Legal consultation",
    その他: "Other",
  },
};

// 案件タイプの逆マッピング（英語→日本語）
const CASE_TYPE_REVERSE_MAPPING: Record<string, string> = {
  "Contract review": "契約書審査",
  "Contract drafting": "契約書起案",
  "Legal consultation": "法務相談",
  Other: "その他",
};

// 部署名のマッピング（20個以上）
const DEPARTMENT_MAPPING: Record<LocaleCode, Record<string, string>> = {
  "ja-JP": {
    営業部: "営業部",
    マーケティング部: "マーケティング部",
    人事部: "人事部",
    開発部: "開発部",
    経理部: "経理部",
    事業開発部: "事業開発部",
    法務部: "法務部",
    総務部: "総務部",
    広報部: "広報部",
    情報システム部: "情報システム部",
    購買部: "購買部",
    カスタマーサポート部: "カスタマーサポート部",
    品質保証部: "品質保証部",
    製造部: "製造部",
    物流部: "物流部",
    研究開発部: "研究開発部",
    デザイン部: "デザイン部",
    海外事業部: "海外事業部",
    コンプライアンス室: "コンプライアンス室",
    経営企画室: "経営企画室",
    秘書室: "秘書室",
    監査室: "監査室",
  },
  "en-US": {
    営業部: "Sales",
    マーケティング部: "Marketing",
    人事部: "HR",
    開発部: "Development",
    経理部: "Accounting",
    事業開発部: "Business Development",
    法務部: "Legal",
    総務部: "General Affairs",
    広報部: "Public Relations",
    情報システム部: "IT",
    購買部: "Purchasing",
    カスタマーサポート部: "Customer Support",
    品質保証部: "Quality Assurance",
    製造部: "Manufacturing",
    物流部: "Logistics",
    研究開発部: "R&D",
    デザイン部: "Design",
    海外事業部: "Overseas Business",
    コンプライアンス室: "Compliance Office",
    経営企画室: "Corporate Planning",
    秘書室: "Secretary Office",
    監査室: "Audit Office",
  },
};

// 契約カテゴリのマッピング
const CONTRACT_CATEGORY_MAPPING: Record<LocaleCode, Record<string, string>> = {
  "ja-JP": {
    取引基本契約: "取引基本契約",
    利用規約: "利用規約",
    秘密保持契約: "秘密保持契約",
    業務委託契約: "業務委託契約",
    販売代理店契約: "販売代理店契約",
    競業避止義務誓約書: "競業避止義務誓約書",
    NDA: "NDA",
    システム開発契約: "システム開発契約",
    スポンサー契約: "スポンサー契約",
    "M&A関連契約": "M&A関連契約",
    顧問契約: "顧問契約",
    不動産賃貸借契約: "不動産賃貸借契約",
  },
  "en-US": {
    取引基本契約: "Master Service Agreement",
    利用規約: "Terms of Service",
    秘密保持契約: "Non-Disclosure Agreement",
    業務委託契約: "Outsourcing Agreement",
    販売代理店契約: "Sales Agency Agreement",
    競業避止義務誓約書: "Non-Compete Agreement",
    NDA: "NDA",
    システム開発契約: "System Development Agreement",
    スポンサー契約: "Sponsorship Agreement",
    "M&A関連契約": "M&A Agreement",
    顧問契約: "Advisory Agreement",
    不動産賃貸借契約: "Real Estate Lease Agreement",
  },
};

// メンバー名のマッピング
export const MEMBER_MAPPING: Record<LocaleCode, Record<string, string>> = {
  "ja-JP": {
    "佐藤 陽子": "佐藤 陽子",
    "鈴木 一郎": "鈴木 一郎",
    "高橋 恵子": "高橋 恵子",
    "田中 健太": "田中 健太",
    "渡辺 直美": "渡辺 直美",
  },
  "en-US": {
    "佐藤 陽子": "Sato Yoko",
    "鈴木 一郎": "Suzuki Ichiro",
    "高橋 恵子": "Takahashi Keiko",
    "田中 健太": "Tanaka Kenta",
    "渡辺 直美": "Watanabe Naomi",
  },
};

// 依頼者名のマッピング（主要なもののみ）
const REQUESTER_MAPPING: Record<LocaleCode, Record<string, string>> = {
  "ja-JP": {
    "田中 太郎": "田中 太郎",
    "鈴木 一郎": "鈴木 一郎",
    "佐藤 花子": "佐藤 花子",
    "渡辺 健太": "渡辺 健太",
    "高橋 直子": "高橋 直子",
    "山田 健一": "山田 健一",
    "佐々木 愛": "佐々木 愛",
    "山口 達也": "山口 達也",
    "井上 智子": "井上 智子",
    "木村 拓也": "木村 拓也",
    "林 真由美": "林 真由美",
    "森 竜一": "森 竜一",
    "池田 久美子": "池田 久美子",
    "石川 さゆり": "石川 さゆり",
    "後藤 輝基": "後藤 輝基",
    "岡田 准一": "岡田 准一",
    "西野 カナ": "西野 カナ",
    "福山 雅治": "福山 雅治",
    "星野 源": "星野 源",
    "綾瀬 はるか": "綾瀬 はるか",
    "新規 顧客": "新規 顧客",
    "既存 顧客": "既存 顧客",
    "パートナー 企業": "パートナー 企業",
    "内部 監査": "内部 監査",
    顧客A: "顧客A",
    顧客B: "顧客B",
    "伊藤 誠": "伊藤 誠",
    "中村 優子": "中村 優子",
    "小林 大輔": "小林 大輔",
    "加藤 美穂": "加藤 美穂",
    "吉田 沙織": "吉田 沙織",
    人事部担当: "人事部担当",
    経理部担当: "経理部担当",
    営業企画部: "営業企画部",
    開発部担当: "開発部担当",
  },
  "en-US": {
    "田中 太郎": "Tanaka Taro",
    "鈴木 一郎": "Suzuki Ichiro",
    "佐藤 花子": "Sato Hanako",
    "渡辺 健太": "Watanabe Kenta",
    "高橋 直子": "Takahashi Naoko",
    "山田 健一": "Yamada Kenichi",
    "佐々木 愛": "Sasaki Ai",
    "山口 達也": "Yamaguchi Tatsuya",
    "井上 智子": "Inoue Tomoko",
    "木村 拓也": "Kimura Takuya",
    "林 真由美": "Hayashi Mayumi",
    "森 竜一": "Mori Ryuichi",
    "池田 久美子": "Ikeda Kumiko",
    "石川 さゆり": "Ishikawa Sayuri",
    "後藤 輝基": "Goto Teruki",
    "岡田 准一": "Okada Junichi",
    "西野 カナ": "Nishino Kana",
    "福山 雅治": "Fukuyama Masaharu",
    "星野 源": "Hoshino Gen",
    "綾瀬 はるか": "Ayase Haruka",
    "新規 顧客": "New Customer",
    "既存 顧客": "Existing Customer",
    "パートナー 企業": "Partner Company",
    "内部 監査": "Internal Audit",
    顧客A: "Customer A",
    顧客B: "Customer B",
    "伊藤 誠": "Ito Makoto",
    "中村 優子": "Nakamura Yuko",
    "小林 大輔": "Kobayashi Daisuke",
    "加藤 美穂": "Kato Miho",
    "吉田 沙織": "Yoshida Saori",
    人事部担当: "HR Representative",
    経理部担当: "Accounting Representative",
    営業企画部: "Sales Planning",
    開発部担当: "Development Representative",
  },
};

// 案件名のマッピング（主要なもののみ、マッピングにないものは元の日本語をそのまま表示）
export const CASE_NAME_MAPPING: Record<LocaleCode, Record<string, string>> = {
  "ja-JP": {
    株式会社Xとの新規取引基本契約のレビュー依頼: "株式会社Xとの新規取引基本契約のレビュー依頼",
    Yサービス利用規約の改定に関するご相談: "Yサービス利用規約の改定に関するご相談",
    "Z社向け秘密保持契約（NDA）の審査をお願いします": "Z社向け秘密保持契約（NDA）の審査をお願いします",
    "【至急】業務委託契約書Eのレビューをお願いします": "【至急】業務委託契約書Eのレビューをお願いします",
    販売代理店契約書Iの法務確認依頼: "販売代理店契約書Iの法務確認依頼",
    新規事業の法的リスクに関する調査依頼: "新規事業の法的リスクに関する調査依頼",
    顧客向け追加契約書の作成をお願いします: "顧客向け追加契約書の作成をお願いします",
    コンプライアンス研修資料のリーガルチェック: "コンプライアンス研修資料のリーガルチェック",
    "Re: 秘密保持誓約書のドラフト作成依頼": "Re: 秘密保持誓約書のドラフト作成依頼",
    システム利用規約の改定案レビュー: "システム利用規約の改定案レビュー",
    利用規約Dの審査をお願いいたします: "利用規約Dの審査をお願いいたします",
    秘密保持契約書Fの作成依頼: "秘密保持契約書Fの作成依頼",
    コンサルティング契約書Gに関する法務相談: "コンサルティング契約書Gに関する法務相談",
    ライセンス契約書Jのドラフト作成: "ライセンス契約書Jのドラフト作成",
    "【契約審査】競業避止義務誓約書のレビュー": "【契約審査】競業避止義務誓約書のレビュー",
    取引基本契約書のひな形作成依頼: "取引基本契約書のひな形作成依頼",
    情報セキュリティポリシーのレビューをお願いします: "情報セキュリティポリシーのレビューをお願いします",
    Webサイトの利用規約を作成したい: "Webサイトの利用規約を作成したい",
    "システム開発契約書Hのレビュー依頼（大至急）": "システム開発契約書Hのレビュー依頼（大至急）",
    プライバシーポリシー改定の件: "プライバシーポリシー改定の件",
    広告掲載に関する契約書の作成: "広告掲載に関する契約書の作成",
    個人情報取扱同意書のひな形について: "個人情報取扱同意書のひな形について",
    不動産賃貸借契約書のレビューをお願いします: "不動産賃貸借契約書のレビューをお願いします",
    業務提携契約書の件でご相談: "業務提携契約書の件でご相談",
    スポンサー契約書の法務レビュー依頼: "スポンサー契約書の法務レビュー依頼",
    "Re: 契約更新の通知方法について": "Re: 契約更新の通知方法について",
    "M&A関連契約書のレビューをお願いいたします": "M&A関連契約書のレビューをお願いいたします",
    知財ライセンス契約のドラフト確認依頼: "知財ライセンス契約のドラフト確認依頼",
    "【法務相談】反社チェックの依頼": "【法務相談】反社チェックの依頼",
    利用規約Zのレビュー依頼: "利用規約Zのレビュー依頼",
    顧問契約書の審査をお願いします: "顧問契約書の審査をお願いします",
    製造委託契約書の作成をお願いしたいのですが: "製造委託契約書の作成をお願いしたいのですが",
    "10月案件(渡辺)の契約書起案": "10月案件(渡辺)の契約書起案",
    "10月案件(田中)の利用規約レビュー": "10月案件(田中)の利用規約レビュー",
    "10月案件(高橋)の法務相談": "10月案件(高橋)の法務相談",
    "11月案件(佐藤)のNDAレビュー": "11月案件(佐藤)のNDAレビュー",
    "11月案件(鈴木)の契約書作成": "11月案件(鈴木)の契約書作成",
    "7月案件(佐藤)の契約書起案": "7月案件(佐藤)の契約書起案",
    "7月案件(渡辺)のその他資料レビュー": "7月案件(渡辺)のその他資料レビュー",
    "7月案件(田中)のNDAレビュー": "7月案件(田中)のNDAレビュー",
    "8月案件(佐藤)の法務相談": "8月案件(佐藤)の法務相談",
    "8月案件(鈴木)の業務委託契約レビュー": "8月案件(鈴木)の業務委託契約レビュー",
    "8月案件(高橋)の契約書作成": "8月案件(高橋)の契約書作成",
    "9月案件(佐藤)のその他資料レビュー": "9月案件(佐藤)のその他資料レビュー",
    "FW: [過去案件] A-2の契約書ドラフト": "FW: [過去案件] A-2の契約書ドラフト",
    "Re: [過去案件] A-1の契約書レビュー": "Re: [過去案件] A-1の契約書レビュー",
    "[過去案件] B-1の法務相談": "[過去案件] B-1の法務相談",
    "[過去案件] C-1 その他資料レビュー": "[過去案件] C-1 その他資料レビュー",
    "[過去案件] C-2 業務委託契約のレビュー依頼": "[過去案件] C-2 業務委託契約のレビュー依頼",
    "[過去案件] D-1 契約書作成依頼": "[過去案件] D-1 契約書作成依頼",
    会計システム導入に関する契約相談: "会計システム導入に関する契約相談",
    営業部向けコンプライアンス研修資料のレビュー: "営業部向けコンプライアンス研修資料のレビュー",
    採用候補者向け秘密保持契約の確認: "採用候補者向け秘密保持契約の確認",
    新規API連携に関する技術提携契約: "新規API連携に関する技術提携契約",
  },
  "en-US": {
    株式会社Xとの新規取引基本契約のレビュー依頼: "Review request for new master service agreement with Company X",
    Yサービス利用規約の改定に関するご相談: "Consultation on revision of Y service terms of service",
    "Z社向け秘密保持契約（NDA）の審査をお願いします": "Review request for non-disclosure agreement (NDA) for Company Z",
    "【至急】業務委託契約書Eのレビューをお願いします": "[Urgent] Review request for outsourcing agreement E",
    販売代理店契約書Iの法務確認依頼: "Legal review request for sales agency agreement I",
    新規事業の法的リスクに関する調査依頼: "Investigation request regarding legal risks of new business",
    顧客向け追加契約書の作成をお願いします: "Request for creation of additional agreement for customers",
    コンプライアンス研修資料のリーガルチェック: "Legal check of compliance training materials",
    "Re: 秘密保持誓約書のドラフト作成依頼": "Re: Request for drafting confidentiality pledge",
    システム利用規約の改定案レビュー: "Review of revised system terms of service",
    利用規約Dの審査をお願いいたします: "Review request for terms of service D",
    秘密保持契約書Fの作成依頼: "Request for creation of non-disclosure agreement F",
    コンサルティング契約書Gに関する法務相談: "Legal consultation regarding consulting agreement G",
    ライセンス契約書Jのドラフト作成: "Drafting of license agreement J",
    "【契約審査】競業避止義務誓約書のレビュー": "[Contract Review] Review of non-compete agreement",
    取引基本契約書のひな形作成依頼: "Request for creation of master service agreement template",
    情報セキュリティポリシーのレビューをお願いします: "Review request for information security policy",
    Webサイトの利用規約を作成したい: "Want to create website terms of service",
    "システム開発契約書Hのレビュー依頼（大至急）": "Review request for system development agreement H (urgent)",
    プライバシーポリシー改定の件: "Privacy policy revision",
    広告掲載に関する契約書の作成: "Creation of agreement regarding advertisement placement",
    個人情報取扱同意書のひな形について: "About personal information handling consent form template",
    不動産賃貸借契約書のレビューをお願いします: "Review request for real estate lease agreement",
    業務提携契約書の件でご相談: "Consultation regarding business partnership agreement",
    スポンサー契約書の法務レビュー依頼: "Legal review request for sponsorship agreement",
    "Re: 契約更新の通知方法について": "Re: About contract renewal notification method",
    "M&A関連契約書のレビューをお願いいたします": "Review request for M&A agreement",
    知財ライセンス契約のドラフト確認依頼: "Draft review request for intellectual property license agreement",
    "【法務相談】反社チェックの依頼": "[Legal Consultation] Request for anti-social forces check",
    利用規約Zのレビュー依頼: "Review request for terms of service Z",
    顧問契約書の審査をお願いします: "Review request for advisory agreement",
    製造委託契約書の作成をお願いしたいのですが: "Would like to request creation of manufacturing outsourcing agreement",
    "10月案件(渡辺)の契約書起案": "October case (Watanabe) - Contract drafting",
    "10月案件(田中)の利用規約レビュー": "October case (Tanaka) - Terms of service review",
    "10月案件(高橋)の法務相談": "October case (Takahashi) - Legal consultation",
    "11月案件(佐藤)のNDAレビュー": "November case (Sato) - NDA review",
    "11月案件(鈴木)の契約書作成": "November case (Suzuki) - Contract creation",
    "7月案件(佐藤)の契約書起案": "July case (Sato) - Contract drafting",
    "7月案件(渡辺)のその他資料レビュー": "July case (Watanabe) - Other document review",
    "7月案件(田中)のNDAレビュー": "July case (Tanaka) - NDA review",
    "8月案件(佐藤)の法務相談": "August case (Sato) - Legal consultation",
    "8月案件(鈴木)の業務委託契約レビュー": "August case (Suzuki) - Outsourcing agreement review",
    "8月案件(高橋)の契約書作成": "August case (Takahashi) - Contract creation",
    "9月案件(佐藤)のその他資料レビュー": "September case (Sato) - Other document review",
    "FW: [過去案件] A-2の契約書ドラフト": "FW: [Past case] A-2 contract draft",
    "Re: [過去案件] A-1の契約書レビュー": "Re: [Past case] A-1 contract review",
    "[過去案件] B-1の法務相談": "[Past case] B-1 legal consultation",
    "[過去案件] C-1 その他資料レビュー": "[Past case] C-1 other document review",
    "[過去案件] C-2 業務委託契約のレビュー依頼": "[Past case] C-2 outsourcing agreement review request",
    "[過去案件] D-1 契約書作成依頼": "[Past case] D-1 contract creation request",
    会計システム導入に関する契約相談: "Contract consultation regarding accounting system implementation",
    営業部向けコンプライアンス研修資料のレビュー: "Review of compliance training materials for sales department",
    採用候補者向け秘密保持契約の確認: "Confirmation of non-disclosure agreement for job candidates",
    新規API連携に関する技術提携契約: "Technical partnership agreement regarding new API integration",
  },
};

// `updatedAt` は本来サービス本体が提供する値。
// このプロトタイプでは、データに `updatedAt` が無いケースもあるため、未設定の場合は `startDate` を `updatedAt` とみなして補完する。
const rawCaseData: CaseData[] = [
  {
    id: 1,
    caseId: 1,
    caseName: "株式会社Xとの新規取引基本契約のレビュー依頼",
    assignee: "",
    status: "未着手",
    caseType: "契約書審査",
    contractCategory: "取引基本契約",
    dueDate: "2025-12-15",
    startDate: "2025-12-01",
    firstReplyDate: "2025-12-02",
    completionDate: "",
    requester: "田中 太郎",
    requestingDepartment: "営業部",
    subAssignee: "鈴木 一郎",
    templateName: "取引基本契約_v2.docx",
    eContractStatus: "署名中",
    storageStatus: "未保管",
    statusHistory: [{ status: "未着手", startDate: "2025-12-01", endDate: null }],
  },
  {
    id: 2,
    caseId: 2,
    caseName: "Yサービス利用規約の改定に関するご相談",
    assignee: "",
    status: "確認中",
    caseType: "契約書起案",
    contractCategory: "利用規約",
    dueDate: "2025-12-10",
    startDate: "2025-12-01",
    firstReplyDate: "2025-12-01",
    completionDate: "",
    requester: "鈴木 一郎",
    requestingDepartment: "マーケティング部",
    subAssignee: "",
    templateName: null,
    eContractStatus: "未署名",
    storageStatus: "未保管",
    statusHistory: [
      { status: "未着手", startDate: "2025-12-01", endDate: "2025-12-01" },
      { status: "確認中", startDate: "2025-12-01", endDate: null },
    ],
  },
  {
    id: 3,
    caseId: 3,
    caseName: "Z社向け秘密保持契約（NDA）の審査をお願いします",
    assignee: "",
    status: "未着手",
    caseType: "契約書審査",
    contractCategory: "秘密保持契約",
    dueDate: "2025-12-08",
    startDate: "2025-12-02",
    firstReplyDate: "2025-12-03",
    completionDate: "2025-12-09",
    requester: "佐藤 花子",
    requestingDepartment: "人事部",
    templateName: "NDA_standard_v3.docx",
    eContractStatus: "署名済み",
    storageStatus: "保管済み",
    statusHistory: [
      { status: "未着手", startDate: "2025-12-02", endDate: "2025-12-03" },
      { status: "確認中", startDate: "2025-12-03", endDate: "2025-12-06" },
      { status: "2次確認中", startDate: "2025-12-06", endDate: "2025-12-09" },
    ],
  },
  {
    id: 5,
    caseId: 5,
    caseName: "【至急】業務委託契約書Eのレビューをお願いします",
    assignee: "佐藤 陽子",
    status: "未着手",
    caseType: "契約書起案",
    dueDate: "2025-12-15",
    startDate: "2025-12-10",
    firstReplyDate: "2025-12-11T10:00:00",
    completionDate: "2025-12-16",
    requester: "渡辺 健太",
    requestingDepartment: "営業部",
    subAssignee: "田中 健太",
    templateName: "業務委託契約_v1.docx",
    eContractStatus: "署名中",
    storageStatus: "未保管",
    statusHistory: [
      { status: "未着手", startDate: "2025-12-10", endDate: "2025-12-11" },
      { status: "確認中", startDate: "2025-12-11", endDate: "2025-12-13" },
      { status: "2次確認中", startDate: "2025-12-13", endDate: "2025-12-15" },
      { status: "自部門外確認中", startDate: "2025-12-15", endDate: "2025-12-16" },
    ],
  },
  {
    id: 9,
    caseId: 9,
    caseName: "販売代理店契約書Iの法務確認依頼",
    assignee: "佐藤 陽子",
    status: "確認中",
    caseType: "契約書審査",
    contractCategory: "販売代理店契約",
    dueDate: "2025-12-07", // 変更: 11 -> 07 (超過)
    startDate: "2025-12-01", // 変更: 06 -> 01
    requester: "高橋 直子",
    requestingDepartment: "開発部",
    subAssignee: "",
    templateName: null,
    eContractStatus: "署名済み",
    storageStatus: "保管済み",
    statusHistory: [
      { status: "未着手", startDate: "2025-12-01", endDate: "2025-12-02" },
      { status: "確認中", startDate: "2025-12-02", endDate: "2025-12-05" },
    ],
  },
  {
    id: 14,
    caseId: 14,
    caseName: "新規事業の法的リスクに関する調査依頼",
    assignee: "佐藤 陽子",
    status: "2次確認中",
    caseType: "法務相談",
    dueDate: "2025-12-16",
    startDate: "2025-12-11",
    firstReplyDate: "2025-12-11T18:30:00",
    completionDate: "2025-12-15",
    requester: "伊藤 誠",
    requestingDepartment: "マーケティング部",
    templateName: null,
    eContractStatus: "未署名",
    storageStatus: "未保管",
    statusHistory: [
      { status: "未着手", startDate: "2025-12-11", endDate: "2025-12-12" },
      { status: "確認中", startDate: "2025-12-12", endDate: "2025-12-14" },
      { status: "2次確認中", startDate: "2025-12-14", endDate: "2025-12-15" },
    ],
  },
  {
    id: 21,
    caseId: 21,
    caseName: "顧客向け追加契約書の作成をお願いします",
    assignee: "佐藤 陽子",
    status: "未着手",
    caseType: "契約書起案",
    dueDate: "2025-12-20",
    startDate: "2025-12-18",
    requester: "中村 優子",
    requestingDepartment: "人事部",
    templateName: "個別契約書_v1.docx",
    eContractStatus: "未署名",
    storageStatus: "未保管",
    statusHistory: [{ status: "未着手", startDate: "2025-12-18", endDate: null }],
  },
  {
    id: 22,
    caseId: 22,
    caseName: "コンプライアンス研修資料のリーガルチェック",
    assignee: "佐藤 陽子",
    status: "確認中",
    caseType: "その他",
    dueDate: "2025-12-25",
    startDate: "2025-12-20",
    requester: "小林 大輔",
    requestingDepartment: "営業部",
    templateName: null,
    eContractStatus: "署名済み",
    storageStatus: "保管済み",
    statusHistory: [
      { status: "未着手", startDate: "2025-12-20", endDate: "2025-12-21" },
      { status: "確認中", startDate: "2025-12-21", endDate: null },
    ],
  },
  {
    id: 23,
    caseId: 23,
    caseName: "Re: 秘密保持誓約書のドラフト作成依頼",
    assignee: "佐藤 陽子",
    status: "未着手",
    caseType: "契約書起案",
    dueDate: "",
    startDate: "2025-12-23",
    requester: "加藤 美穂",
    requestingDepartment: "開発部",
    templateName: "秘密保持誓約書_v2.docx",
    eContractStatus: "署名中",
    storageStatus: "未保管",
    statusHistory: [{ status: "未着手", startDate: "2025-12-23", endDate: null }],
  },
  {
    id: 24,
    caseId: 24,
    caseName: "システム利用規約の改定案レビュー",
    assignee: "佐藤 陽子",
    status: "自部門外確認中",
    caseType: "その他",
    dueDate: "2025-12-10", // 〜3日後
    startDate: "2025-12-01",
    firstReplyDate: "2025-12-02T09:00:00",
    completionDate: "2025-12-06",
    requester: "吉田 沙織",
    requestingDepartment: "マーケティング部",
    templateName: null,
    eContractStatus: "署名済み",
    storageStatus: "未保管",
    statusHistory: [
      { status: "未着手", startDate: "2025-12-01", endDate: "2025-12-02" },
      { status: "確認中", startDate: "2025-12-02", endDate: "2025-12-04" },
      { status: "自部門外確認中", startDate: "2025-12-04", endDate: "2025-12-06" },
    ],
  },
  // 鈴木 一郎: 8件
  {
    id: 4,
    caseId: 4,
    caseName: "利用規約Dの審査をお願いいたします",
    assignee: "鈴木 一郎",
    status: "確認中",
    caseType: "契約書審査",
    contractCategory: "利用規約",
    dueDate: "2025-12-08", // 今日まで
    startDate: "2025-12-05",
    requester: "山田 健一",
    requestingDepartment: "人事部",
    templateName: null,
    eContractStatus: "署名中",
    storageStatus: "未保管",
    statusHistory: [
      { status: "未着手", startDate: "2025-12-05", endDate: "2025-12-06" },
      { status: "確認中", startDate: "2025-12-06", endDate: null },
    ],
  },
  {
    id: 6,
    caseId: 6,
    caseName: "秘密保持契約書Fの作成依頼",
    assignee: "鈴木 一郎",
    status: "自部門外確認中",
    caseType: "契約書起案",
    dueDate: "2025-12-25",
    startDate: "2025-12-20",
    firstReplyDate: "2025-12-20T11:00:00",
    completionDate: "2025-12-26",
    requester: "佐々木 愛",
    requestingDepartment: "営業部",
    templateName: "秘密保持契約書_v4.docx",
    eContractStatus: "署名済み",
    storageStatus: "保管済み",
    statusHistory: [
      { status: "未着手", startDate: "2025-12-20", endDate: "2025-12-21" },
      { status: "確認中", startDate: "2025-12-21", endDate: "2025-12-23" },
      { status: "自部門外確認中", startDate: "2025-12-23", endDate: "2025-12-26" },
    ],
  },
  {
    id: 7,
    caseId: 7,
    caseName: "コンサルティング契約書Gに関する法務相談",
    assignee: "鈴木 一郎",
    status: "確認中",
    caseType: "法務相談",
    dueDate: "2025-12-18",
    startDate: "2025-12-13",
    requester: "山口 達也",
    requestingDepartment: "開発部",
    templateName: null,
    eContractStatus: "未署名",
    storageStatus: "未保管",
    statusHistory: [
      { status: "未着手", startDate: "2025-12-13", endDate: "2025-12-14" },
      { status: "確認中", startDate: "2025-12-14", endDate: null },
    ],
  },
  {
    id: 10,
    caseId: 10,
    caseName: "ライセンス契約書Jのドラフト作成",
    assignee: "鈴木 一郎",
    status: "未着手",
    caseType: "契約書起案",
    dueDate: "2025-12-14",
    startDate: "2025-12-10",
    requester: "井上 智子",
    requestingDepartment: "マーケティング部",
    templateName: "ライセンス契約書_v1.docx",
    eContractStatus: "未署名",
    storageStatus: "未保管",
    statusHistory: [{ status: "未着手", startDate: "2025-12-10", endDate: null }],
  },
  {
    id: 15,
    caseId: 15,
    caseName: "【契約審査】競業避止義務誓約書のレビュー",
    assignee: "鈴木 一郎",
    status: "確認中",
    caseType: "契約書審査",
    contractCategory: "競業避止義務誓約書",
    dueDate: "2025-12-22",
    startDate: "2025-12-18",
    firstReplyDate: "2025-12-19T15:00:00",
    completionDate: "2025-12-21",
    requester: "木村 拓也",
    requestingDepartment: "人事部",
    templateName: null,
    eContractStatus: "署名済み",
    storageStatus: "保管済み",
    statusHistory: [
      { status: "未着手", startDate: "2025-12-18", endDate: "2025-12-19" },
      { status: "確認中", startDate: "2025-12-19", endDate: "2025-12-21" },
    ],
  },
  {
    id: 25,
    caseId: 25,
    caseName: "取引基本契約書のひな形作成依頼",
    assignee: "鈴木 一郎",
    status: "2次確認中",
    caseType: "契約書起案",
    dueDate: "2025-12-11", // 〜3日後
    startDate: "2025-12-01",
    requester: "林 真由美",
    requestingDepartment: "営業部",
    templateName: "取引基本契約書_v3.docx",
    eContractStatus: "署名中",
    storageStatus: "未保管",
    statusHistory: [
      { status: "未着手", startDate: "2025-12-01", endDate: "2025-12-02" },
      { status: "確認中", startDate: "2025-12-02", endDate: "2025-12-05" },
      { status: "2次確認中", startDate: "2025-12-05", endDate: null },
    ],
  },
  {
    id: 26,
    caseId: 26,
    caseName: "情報セキュリティポリシーのレビューをお願いします",
    assignee: "鈴木 一郎",
    status: "確認中",
    caseType: "その他",
    dueDate: "2025-12-28",
    startDate: "2025-12-23",
    requester: "森 竜一",
    requestingDepartment: "開発部",
    templateName: null,
    eContractStatus: "署名済み",
    storageStatus: "保管済み",
    statusHistory: [
      { status: "未着手", startDate: "2025-12-23", endDate: "2025-12-24" },
      { status: "確認中", startDate: "2025-12-24", endDate: null },
    ],
  },
  {
    id: 27,
    caseId: 27,
    caseName: "Webサイトの利用規約を作成したい",
    assignee: "鈴木 一郎",
    status: "未着手",
    caseType: "契約書起案",
    dueDate: "",
    startDate: "2025-12-25",
    firstReplyDate: "2025-12-26T12:00:00",
    completionDate: "2025-12-28",
    requester: "池田 久美子",
    requestingDepartment: "マーケティング部",
    templateName: "Webサイト利用規約_v1.docx",
    eContractStatus: "署名済み",
    storageStatus: "保管済み",
    statusHistory: [
      { status: "未着手", startDate: "2025-12-25", endDate: "2025-12-26" },
      { status: "確認中", startDate: "2025-12-26", endDate: "2025-12-28" },
    ],
  },
  // 高橋 恵子: 6件
  {
    id: 8,
    caseId: 8,
    caseName: "システム開発契約書Hのレビュー依頼（大至急）",
    assignee: "高橋 恵子",
    status: "2次確認中",
    caseType: "契約書審査",
    contractCategory: "システム開発契約",
    dueDate: "2025-12-06", // 変更: 20 -> 06 (超過)
    startDate: "2025-12-01", // 変更: 15 -> 01
    requester: "橋本 奈々",
    requestingDepartment: "人事部",
    templateName: null,
    eContractStatus: "署名中",
    storageStatus: "未保管",
    statusHistory: [
      { status: "未着手", startDate: "2025-12-01", endDate: "2025-12-02" },
      { status: "確認中", startDate: "2025-12-02", endDate: "2025-12-04" },
      { status: "2次確認中", startDate: "2025-12-04", endDate: null },
    ],
  },
  {
    id: 11,
    caseId: 11,
    caseName: "プライバシーポリシー改定の件",
    assignee: "高橋 恵子",
    status: "確認中",
    caseType: "その他",
    dueDate: "2025-12-11",
    startDate: "2025-12-06",
    firstReplyDate: "2025-12-06T19:00:00",
    completionDate: "2025-12-10",
    requester: "石川 さゆり",
    requestingDepartment: "営業部",
    templateName: null,
    eContractStatus: "署名済み",
    storageStatus: "保管済み",
    statusHistory: [
      { status: "未着手", startDate: "2025-12-06", endDate: "2025-12-06" },
      { status: "確認中", startDate: "2025-12-06", endDate: "2025-12-10" },
    ],
  },
  {
    id: 12,
    caseId: 12,
    caseName: "広告掲載に関する契約書の作成",
    assignee: "高橋 恵子",
    status: "未着手",
    caseType: "契約書起案",
    dueDate: "2025-12-17", // 10
    startDate: "2025-12-03",
    requester: "後藤 輝基",
    requestingDepartment: "開発部",
    templateName: "広告掲載契約書_v1.docx",
    eContractStatus: "未署名",
    storageStatus: "未保管",
    statusHistory: [{ status: "未着手", startDate: "2025-12-03", endDate: null }],
  },
  {
    id: 16,
    caseId: 16,
    caseName: "個人情報取扱同意書のひな形について",
    assignee: "高橋 恵子",
    status: "未着手",
    caseType: "契約書起案",
    dueDate: "2025-12-12",
    startDate: "2025-12-07",
    requester: "岡田 准一",
    requestingDepartment: "マーケティング部",
    templateName: "個人情報取扱同意書_v1.docx",
    eContractStatus: "未署名",
    storageStatus: "未保管",
    statusHistory: [{ status: "未着手", startDate: "2025-12-07", endDate: null }],
  },
  {
    id: 28,
    caseId: 28,
    caseName: "不動産賃貸借契約書のレビューをお願いします",
    assignee: "高橋 恵子",
    status: "確認中",
    caseType: "契約書審査",
    contractCategory: "不動産賃貸借契約",
    dueDate: "2025-12-19",
    startDate: "2025-12-14",
    firstReplyDate: "2025-12-15T09:30:00",
    completionDate: "2025-12-18",
    requester: "西野 カナ",
    requestingDepartment: "人事部",
    templateName: null,
    eContractStatus: "署名済み",
    storageStatus: "保管済み",
    statusHistory: [
      { status: "未着手", startDate: "2025-12-14", endDate: "2025-12-15" },
      { status: "確認中", startDate: "2025-12-15", endDate: "2025-12-18" },
    ],
  },
  {
    id: 29,
    caseId: 29,
    caseName: "業務提携契約書の件でご相談",
    assignee: "高橋 恵子",
    status: "自部門外確認中",
    caseType: "契約書起案",
    dueDate: "2025-12-10", // 〜3日後
    startDate: "2025-11-28",
    requester: "福山 雅治",
    requestingDepartment: "営業部",
    templateName: "業務提携契約書_v2.docx",
    eContractStatus: "署名中",
    storageStatus: "未保管",
    statusHistory: [
      { status: "未着手", startDate: "2025-11-28", endDate: "2025-11-29" },
      { status: "確認中", startDate: "2025-11-29", endDate: "2025-12-02" },
      { status: "自部門外確認中", startDate: "2025-12-02", endDate: null },
    ],
  },
  // 渡辺 直美: 4件
  {
    id: 13,
    caseId: 13,
    caseName: "スポンサー契約書の法務レビュー依頼",
    assignee: "渡辺 直美",
    status: "確認中",
    caseType: "契約書審査",
    contractCategory: "スポンサー契約",
    dueDate: "2025-12-08", // 今日まで
    startDate: "2025-12-04",
    requester: "星野 源",
    requestingDepartment: "開発部",
    templateName: null,
    eContractStatus: "署名済み",
    storageStatus: "未保管",
    statusHistory: [
      { status: "未着手", startDate: "2025-12-04", endDate: "2025-12-05" },
      { status: "確認中", startDate: "2025-12-05", endDate: null },
    ],
  },
  {
    id: 18,
    caseId: 18,
    caseName: "Re: 契約更新の通知方法について",
    assignee: "渡辺 直美",
    status: "確認中",
    caseType: "その他",
    dueDate: "2025-12-13",
    startDate: "2025-12-08",
    firstReplyDate: "2025-12-09T17:00:00",
    completionDate: "2025-12-12",
    requester: "綾瀬 はるか",
    requestingDepartment: "マーケティング部",
    templateName: null,
    eContractStatus: "署名済み",
    storageStatus: "保管済み",
    statusHistory: [
      { status: "未着手", startDate: "2025-12-08", endDate: "2025-12-09" },
      { status: "確認中", startDate: "2025-12-09", endDate: "2025-12-12" },
    ],
  },
  {
    id: 20,
    caseId: 20,
    caseName: "M&A関連契約書のレビューをお願いいたします",
    assignee: "渡辺 直美",
    status: "確認中",
    caseType: "契約書審査",
    contractCategory: "M&A関連契約",
    dueDate: "",
    startDate: "2025-12-10",
    requester: "新規 顧客",
    requestingDepartment: "営業部",
    templateName: null,
    eContractStatus: "署名中",
    storageStatus: "未保管",
    statusHistory: [
      { status: "未着手", startDate: "2025-12-10", endDate: "2025-12-11" },
      { status: "確認中", startDate: "2025-12-11", endDate: null },
    ],
  },
  {
    id: 30,
    caseId: 30,
    caseName: "知財ライセンス契約のドラフト確認依頼",
    assignee: "渡辺 直美",
    status: "2次確認中",
    caseType: "契約書起案",
    dueDate: "2025-12-24",
    startDate: "2025-12-19",
    firstReplyDate: "2025-12-22T11:00:00",
    completionDate: "2025-12-23",
    requester: "既存 顧客",
    requestingDepartment: "マーケティング部",
    templateName: "知財ライセンス契約_v1.docx",
    eContractStatus: "署名済み",
    storageStatus: "保管済み",
    statusHistory: [
      { status: "未着手", startDate: "2025-12-19", endDate: "2025-12-22" },
      { status: "2次確認中", startDate: "2025-12-22", endDate: "2025-12-23" },
    ],
  },
  // 田中 健太: 4件
  {
    id: 17,
    caseId: 17,
    caseName: "【法務相談】反社チェックの依頼",
    assignee: "田中 健太",
    status: "未着手", // 変更: 自部門外確認中 -> 未着手
    caseType: "法務相談",
    dueDate: "2025-12-04", // 変更: 30 -> 04 (超過)
    startDate: "2025-12-01", // 変更: 25 -> 01
    requester: "パートナー 企業",
    requestingDepartment: "事業開発部",
    templateName: null,
    eContractStatus: "未署名",
    storageStatus: "未保管",
    statusHistory: [{ status: "未着手", startDate: "2025-12-01", endDate: null }],
  },
  {
    id: 19,
    caseId: 19,
    caseName: "利用規約Zのレビュー依頼",
    assignee: "田中 健太",
    status: "未着手",
    caseType: "その他",
    dueDate: "",
    startDate: "2025-12-28",
    firstReplyDate: "2025-12-28T14:00:00",
    completionDate: "2025-12-29",
    requester: "内部 監査",
    requestingDepartment: "経理部",
    templateName: null,
    eContractStatus: "署名済み",
    storageStatus: "保管済み",
    statusHistory: [
      { status: "未着手", startDate: "2025-12-28", endDate: "2025-12-28" },
      { status: "確認中", startDate: "2025-12-28", endDate: "2025-12-29" },
    ],
  },
  {
    id: 31,
    caseId: 31,
    caseName: "顧問契約書の審査をお願いします",
    assignee: "田中 健太",
    status: "確認中",
    caseType: "契約書審査",
    contractCategory: "顧問契約",
    dueDate: "2025-12-09", // 〜3日後
    startDate: "2025-12-01",
    requester: "顧客A",
    requestingDepartment: "営業部",
    templateName: "顧問契約書_v1.docx",
    eContractStatus: "署名中",
    storageStatus: "未保管",
    statusHistory: [
      { status: "未着手", startDate: "2025-12-01", endDate: "2025-12-02" },
      { status: "確認中", startDate: "2025-12-02", endDate: null },
    ],
  },
  {
    id: 32,
    caseId: 32,
    caseName: "製造委託契約書の作成をお願いしたいのですが",
    assignee: "田中 健太",
    status: "未着手",
    caseType: "契約書起案",
    dueDate: "2025-12-26",
    startDate: "2025-12-21",
    firstReplyDate: "2025-12-22T16:00:00",
    completionDate: "2025-12-25",
    requester: "顧客B",
    requestingDepartment: "開発部",
    templateName: null,
    eContractStatus: "署名済み",
    storageStatus: "保管済み",
    statusHistory: [
      { status: "未着手", startDate: "2025-12-21", endDate: "2025-12-22" },
      { status: "確認中", startDate: "2025-12-22", endDate: "2025-12-25" },
    ],
  },

  // --- 既存の過去データ ---
  {
    id: 101,
    caseId: 101,
    caseName: "Re: [過去案件] A-1の契約書レビュー",
    assignee: "佐藤 陽子",
    status: "自部門外確認中",
    caseType: "契約書審査",
    contractCategory: "NDA",
    dueDate: "2025-09-15",
    startDate: "2025-09-10",
    firstReplyDate: "2025-09-10T11:00:00",
    completionDate: "2025-09-14",
    requester: "田中 太郎",
    requestingDepartment: "営業部",
    templateName: "NDA_standard_v2.docx",
    eContractStatus: "署名済み",
    storageStatus: "保管済み",
    statusHistory: [
      { status: "未着手", startDate: "2025-09-10", endDate: "2025-09-10" },
      { status: "確認中", startDate: "2025-09-10", endDate: "2025-09-12" },
      { status: "自部門外確認中", startDate: "2025-09-12", endDate: "2025-09-14" },
    ],
  },
  {
    id: 102,
    caseId: 102,
    caseName: "FW: [過去案件] A-2の契約書ドラフト",
    assignee: "佐藤 陽子",
    status: "自部門外確認中",
    caseType: "契約書起案",
    dueDate: "2025-10-20",
    startDate: "2025-10-15",
    firstReplyDate: "2025-10-15T15:30:00",
    completionDate: "2025-10-19",
    requester: "鈴木 一郎",
    requestingDepartment: "マーケティング部",
    templateName: "取引基本契約書_v1.docx",
    eContractStatus: "署名済み",
    storageStatus: "保管済み",
    statusHistory: [
      { status: "未着手", startDate: "2025-10-15", endDate: "2025-10-15" },
      { status: "確認中", startDate: "2025-10-15", endDate: "2025-10-17" },
      { status: "自部門外確認中", startDate: "2025-10-17", endDate: "2025-10-19" },
    ],
  },
  {
    id: 103,
    caseId: 103,
    caseName: "[過去案件] B-1の法務相談",
    assignee: "鈴木 一郎",
    status: "自部門外確認中",
    caseType: "法務相談",
    dueDate: "2025-09-25",
    startDate: "2025-09-22",
    firstReplyDate: "2025-09-23T10:00:00",
    completionDate: "2025-09-24",
    requester: "佐藤 花子",
    requestingDepartment: "人事部",
    templateName: null,
    eContractStatus: "未署名",
    storageStatus: "未保管",
    statusHistory: [
      { status: "未着手", startDate: "2025-09-22", endDate: "2025-09-23" },
      { status: "確認中", startDate: "2025-09-23", endDate: "2025-09-24" },
    ],
  },
  {
    id: 104,
    caseId: 104,
    caseName: "[過去案件] C-1 その他資料レビュー",
    assignee: "高橋 恵子",
    status: "自部門外確認中",
    caseType: "その他",
    dueDate: "2025-10-05",
    startDate: "2025-10-01",
    firstReplyDate: "2025-10-01T13:00:00",
    completionDate: "2025-10-04",
    requester: "渡辺 健太",
    requestingDepartment: "営業部",
    templateName: null,
    eContractStatus: "署名済み",
    storageStatus: "保管済み",
    statusHistory: [
      { status: "未着手", startDate: "2025-10-01", endDate: "2025-10-01" },
      { status: "確認中", startDate: "2025-10-01", endDate: "2025-10-04" },
    ],
  },
  {
    id: 105,
    caseId: 105,
    caseName: "[過去案件] C-2 業務委託契約のレビュー依頼",
    assignee: "高橋 恵子",
    status: "自部門外確認中",
    caseType: "契約書審査",
    contractCategory: "業務委託契約",
    dueDate: "2025-10-12",
    startDate: "2025-10-08",
    firstReplyDate: "2025-10-09T09:00:00",
    completionDate: "2025-10-13",
    requester: "高橋 直子",
    requestingDepartment: "開発部",
    templateName: null,
    eContractStatus: "署名済み",
    storageStatus: "未保管",
    statusHistory: [
      { status: "未着手", startDate: "2025-10-08", endDate: "2025-10-09" },
      { status: "確認中", startDate: "2025-10-09", endDate: "2025-10-13" },
    ],
  },
  {
    id: 106,
    caseId: 106,
    caseName: "[過去案件] D-1 契約書作成依頼",
    assignee: "田中 健太",
    status: "自部門外確認中",
    caseType: "契約書起案",
    dueDate: "2025-09-30",
    startDate: "2025-09-26",
    firstReplyDate: "2025-09-26T18:00:00",
    completionDate: "2025-09-29",
    requester: "伊藤 誠",
    requestingDepartment: "マーケティング部",
    templateName: "SOW_standard_v2.docx",
    eContractStatus: "署名済み",
    storageStatus: "保管済み",
    statusHistory: [
      { status: "未着手", startDate: "2025-09-26", endDate: "2025-09-26" },
      { status: "確認中", startDate: "2025-09-26", endDate: "2025-09-29" },
    ],
  },

  // --- ここから追加データ ---
  // --- 11月
  {
    id: 201,
    caseId: 201,
    caseName: "11月案件(佐藤)のNDAレビュー",
    assignee: "佐藤 陽子",
    status: "自部門外確認中",
    caseType: "契約書審査",
    contractCategory: "NDA",
    dueDate: "2025-11-20",
    startDate: "2025-11-15",
    firstReplyDate: "2025-11-15T10:00:00",
    completionDate: "2025-11-19",
    requester: "中村 優子",
    requestingDepartment: "人事部",
    templateName: "NDA_standard_v3.docx",
    eContractStatus: "署名済み",
    storageStatus: "保管済み",
    statusHistory: [
      { status: "未着手", startDate: "2025-11-15", endDate: "2025-11-15" },
      { status: "確認中", startDate: "2025-11-15", endDate: "2025-11-17" },
      { status: "自部門外確認中", startDate: "2025-11-17", endDate: "2025-11-19" },
    ],
  },
  {
    id: 202,
    caseId: 202,
    caseName: "11月案件(鈴木)の契約書作成",
    assignee: "鈴木 一郎",
    status: "自部門外確認中",
    caseType: "契約書起案",
    dueDate: "2025-11-18",
    startDate: "2025-11-12",
    firstReplyDate: "2025-11-13T14:00:00",
    completionDate: "2025-11-17",
    requester: "小林 大輔",
    requestingDepartment: "営業部",
    templateName: "業務委託契約_v1.docx",
    eContractStatus: "署名済み",
    storageStatus: "保管済み",
    statusHistory: [
      { status: "未着手", startDate: "2025-11-12", endDate: "2025-11-13" },
      { status: "確認中", startDate: "2025-11-13", endDate: "2025-11-15" },
      { status: "自部門外確認中", startDate: "2025-11-15", endDate: "2025-11-17" },
    ],
  },

  // --- 10月
  {
    id: 203,
    caseId: 203,
    caseName: "10月案件(高橋)の法務相談",
    assignee: "高橋 恵子",
    status: "自部門外確認中",
    caseType: "法務相談",
    dueDate: "2025-10-25",
    startDate: "2025-10-20",
    firstReplyDate: "2025-10-20T11:00:00",
    completionDate: "2025-10-24",
    requester: "加藤 美穂",
    requestingDepartment: "開発部",
    templateName: null,
    eContractStatus: "未署名",
    storageStatus: "未保管",
    statusHistory: [
      { status: "未着手", startDate: "2025-10-20", endDate: "2025-10-20" },
      { status: "確認中", startDate: "2025-10-20", endDate: "2025-10-22" },
      { status: "自部門外確認中", startDate: "2025-10-22", endDate: "2025-10-24" },
    ],
  },
  {
    id: 204,
    caseId: 204,
    caseName: "10月案件(田中)の利用規約レビュー",
    assignee: "田中 健太",
    status: "自部門外確認中",
    caseType: "契約書審査",
    contractCategory: "利用規約",
    dueDate: "2025-10-22",
    startDate: "2025-10-18",
    firstReplyDate: "2025-10-19T09:30:00",
    completionDate: "2025-10-21",
    requester: "吉田 沙織",
    requestingDepartment: "マーケティング部",
    templateName: null,
    eContractStatus: "署名済み",
    storageStatus: "未保管",
    statusHistory: [
      { status: "未着手", startDate: "2025-10-18", endDate: "2025-10-19" },
      { status: "確認中", startDate: "2025-10-19", endDate: "2025-10-21" },
    ],
  },
  {
    id: 205,
    caseId: 205,
    caseName: "10月案件(渡辺)の契約書起案",
    assignee: "渡辺 直美",
    status: "自部門外確認中",
    caseType: "契約書起案",
    dueDate: "2025-10-30",
    startDate: "2025-10-25",
    firstReplyDate: "2025-10-26T16:00:00",
    completionDate: "2025-10-29",
    requester: "山田 健一",
    requestingDepartment: "人事部",
    templateName: "SOW_short_v1.docx",
    eContractStatus: "署名済み",
    storageStatus: "保管済み",
    statusHistory: [
      { status: "未着手", startDate: "2025-10-25", endDate: "2025-10-26" },
      { status: "確認中", startDate: "2025-10-26", endDate: "2025-10-28" },
      { status: "自部門外確認中", startDate: "2025-10-28", endDate: "2025-10-29" },
    ],
  },

  // --- 9月
  {
    id: 206,
    caseId: 206,
    caseName: "9月案件(佐藤)のその他資料レビュー",
    assignee: "佐藤 陽子",
    status: "自部門外確認中",
    caseType: "その他",
    dueDate: "2025-09-10",
    startDate: "2025-09-05",
    firstReplyDate: "2025-09-05T17:00:00",
    completionDate: "2025-09-09",
    requester: "佐々木 愛",
    requestingDepartment: "営業部",
    templateName: null,
    eContractStatus: "署名済み",
    storageStatus: "保管済み",
    statusHistory: [
      { status: "未着手", startDate: "2025-09-05", endDate: "2025-09-06" },
      { status: "確認中", startDate: "2025-09-06", endDate: "2025-09-09" },
    ],
  },

  // --- 8月
  {
    id: 207,
    caseId: 207,
    caseName: "8月案件(鈴木)の業務委託契約レビュー",
    assignee: "鈴木 一郎",
    status: "自部門外確認中",
    caseType: "契約書審査",
    contractCategory: "業務委託契約",
    dueDate: "2025-08-15",
    startDate: "2025-08-10",
    firstReplyDate: "2025-08-11T10:00:00",
    completionDate: "2025-08-16",
    requester: "山口 達也",
    requestingDepartment: "開発部",
    templateName: null,
    eContractStatus: "署名済み",
    storageStatus: "未保管",
    statusHistory: [
      { status: "未着手", startDate: "2025-08-10", endDate: "2025-08-11" },
      { status: "確認中", startDate: "2025-08-11", endDate: "2025-08-16" },
    ],
  },
  {
    id: 208,
    caseId: 208,
    caseName: "8月案件(高橋)の契約書作成",
    assignee: "高橋 恵子",
    status: "自部門外確認中",
    caseType: "契約書起案",
    dueDate: "2025-08-20",
    startDate: "2025-08-15",
    firstReplyDate: "2025-08-16T11:00:00",
    completionDate: "2025-08-19",
    requester: "井上 智子",
    requestingDepartment: "マーケティング部",
    templateName: "NDA_simple_v1.2.docx",
    eContractStatus: "署名済み",
    storageStatus: "保管済み",
    statusHistory: [
      { status: "未着手", startDate: "2025-08-15", endDate: "2025-08-16" },
      { status: "確認中", startDate: "2025-08-16", endDate: "2025-08-19" },
    ],
  },
  {
    id: 209,
    caseId: 209,
    caseName: "8月案件(佐藤)の法務相談",
    assignee: "佐藤 陽子",
    status: "自部門外確認中",
    caseType: "法務相談",
    dueDate: "2025-08-25",
    startDate: "2025-08-22",
    firstReplyDate: "2025-08-22T15:00:00",
    completionDate: "2025-08-24",
    requester: "木村 拓也",
    requestingDepartment: "人事部",
    templateName: null,
    eContractStatus: "未署名",
    storageStatus: "未保管",
    statusHistory: [{ status: "未着手", startDate: "2025-08-22", endDate: "2025-08-24" }],
  },

  // --- 7月
  {
    id: 210,
    caseId: 210,
    caseName: "7月案件(田中)のNDAレビュー",
    assignee: "田中 健太",
    status: "自部門外確認中",
    caseType: "契約書審査",
    contractCategory: "NDA",
    dueDate: "2025-07-10",
    startDate: "2025-07-05",
    firstReplyDate: "2025-07-06T09:00:00",
    completionDate: "2025-07-09",
    requester: "林 真由美",
    requestingDepartment: "営業部",
    templateName: "NDA_standard_v3.docx",
    eContractStatus: "署名済み",
    storageStatus: "保管済み",
    statusHistory: [
      { status: "未着手", startDate: "2025-07-05", endDate: "2025-07-06" },
      { status: "確認中", startDate: "2025-07-06", endDate: "2025-07-09" },
    ],
  },
  {
    id: 211,
    caseId: 211,
    caseName: "7月案件(渡辺)のその他資料レビュー",
    assignee: "渡辺 直美",
    status: "自部門外確認中",
    caseType: "その他",
    dueDate: "2025-07-18",
    startDate: "2025-07-12",
    firstReplyDate: "2025-07-13T13:00:00",
    completionDate: "2025-07-17",
    requester: "森 竜一",
    requestingDepartment: "開発部",
    templateName: null,
    eContractStatus: "署名済み",
    storageStatus: "保管済み",
    statusHistory: [
      { status: "未着手", startDate: "2025-07-12", endDate: "2025-07-13" },
      { status: "確認中", startDate: "2025-07-13", endDate: "2025-07-17" },
    ],
  },
  {
    id: 212,
    caseId: 212,
    caseName: "7月案件(佐藤)の契約書起案",
    assignee: "佐藤 陽子",
    status: "自部門外確認中",
    caseType: "契約書起案",
    dueDate: "2025-07-28",
    startDate: "2025-07-22",
    firstReplyDate: "2025-07-23T18:00:00",
    completionDate: "2025-07-29",
    requester: "池田 久美子",
    requestingDepartment: "マーケティング部",
    templateName: "SOW_standard_v2.docx",
    eContractStatus: "署名済み",
    storageStatus: "保管済み",
    statusHistory: [
      { status: "未着手", startDate: "2025-07-22", endDate: "2025-07-23" },
      { status: "確認中", startDate: "2025-07-23", endDate: "2025-07-25" },
    ],
  },
  {
    id: 213,
    caseId: 213,
    caseName: "採用候補者向け秘密保持契約の確認",
    assignee: "田中 健太",
    status: "確認中",
    caseType: "契約書審査",
    contractCategory: "秘密保持契約",
    dueDate: "2025-11-20",
    startDate: "2025-11-12",
    requester: "人事部担当",
    requestingDepartment: "人事部",
    templateName: "秘密保持契約_v4.docx",
    eContractStatus: "署名中",
    storageStatus: "未保管",
    statusHistory: [
      { status: "未着手", startDate: "2025-11-12", endDate: "2025-11-12" },
      { status: "確認中", startDate: "2025-11-12", endDate: "2025-11-13" },
      { status: "自部門外確認中", startDate: "2025-11-13", endDate: "2025-11-15" },
    ],
  },
  {
    id: 214,
    caseId: 214,
    caseName: "会計システム導入に関する契約相談",
    assignee: "鈴木 一郎",
    status: "未着手",
    caseType: "法務相談",
    dueDate: "2025-11-25",
    startDate: "2025-11-15",
    requester: "経理部担当",
    requestingDepartment: "経理部",
    templateName: null,
    eContractStatus: "未署名",
    storageStatus: "未保管",
    statusHistory: [
      { status: "未着手", startDate: "2025-11-15", endDate: "2025-11-15" },
      { status: "確認中", startDate: "2025-11-15", endDate: "2025-11-17" },
      { status: "自部門外確認中", startDate: "2025-11-17", endDate: "2025-11-20" },
    ],
  },
  {
    id: 215,
    caseId: 215,
    caseName: "営業部向けコンプライアンス研修資料のレビュー",
    assignee: "佐藤 陽子",
    status: "確認中",
    caseType: "その他",
    dueDate: "2025-11-28",
    startDate: "2025-11-18",
    requester: "営業企画部",
    requestingDepartment: "営業部",
    templateName: null,
    eContractStatus: "署名済み",
    storageStatus: "保管済み",
    statusHistory: [
      { status: "未着手", startDate: "2025-11-18", endDate: "2025-11-18" },
      { status: "確認中", startDate: "2025-11-18", endDate: "2025-11-20" },
    ],
  },
  {
    id: 216,
    caseId: 216,
    caseName: "新規API連携に関する技術提携契約",
    assignee: "高橋 恵子",
    status: "2次確認中",
    caseType: "契約書起案",
    dueDate: "2025-11-30",
    startDate: "2025-11-20",
    requester: "開発部担当",
    requestingDepartment: "開発部",
    templateName: "技術提携契約_v1.docx",
    eContractStatus: "署名中",
    storageStatus: "未保管",
    statusHistory: [
      { status: "未着手", startDate: "2025-11-20", endDate: "2025-11-20" },
      { status: "確認中", startDate: "2025-11-20", endDate: "2025-11-22" },
      { status: "2次確認中", startDate: "2025-11-22", endDate: "2025-11-23" },
    ],
  },
];

export const caseData: CaseData[] = rawCaseData.map((c) => ({
  ...c,
  // `completionDate` が入っている案件は「完了」ステータスとして扱う（データの整合を取る）
  status: c.completionDate ? "完了" : c.status,
  updatedAt: c.updatedAt ?? c.startDate,
}));

// ロケール対応ステータス名取得関数（フィルタリング用）
export const getLocalizedStatus = (locale: LocaleCode, status: string): string => {
  return STATUS_MAPPING[locale][status] || status;
};

// ロケール対応ステータス名から日本語キーに変換（フィルタリング用）
export const getJapaneseStatus = (localizedStatus: string): string => {
  return STATUS_REVERSE_MAPPING[localizedStatus] || localizedStatus;
};

// ロケール対応案件タイプ名取得関数（フィルタリング用）
export const getLocalizedCaseType = (locale: LocaleCode, caseType: string): string => {
  return CASE_TYPE_MAPPING[locale][caseType] || caseType;
};

// ロケール対応案件タイプ名から日本語キーに変換（フィルタリング用）
export const getJapaneseCaseType = (localizedCaseType: string): string => {
  return CASE_TYPE_REVERSE_MAPPING[localizedCaseType] || localizedCaseType;
};

// ロケール対応データ取得関数
// 内部では日本語キーを維持し、表示用のフィールドのみをロケールに応じて変換
export const getLocalizedCaseData = (locale: LocaleCode): CaseData[] => {
  return caseData.map((c) => {
    const originalStatus = c.completionDate ? "完了" : c.status;
    const localizedStatus = STATUS_MAPPING[locale][originalStatus] || originalStatus;
    const localizedCaseType = CASE_TYPE_MAPPING[locale][c.caseType] || c.caseType;
    const localizedCaseName = CASE_NAME_MAPPING[locale][c.caseName] || c.caseName;
    const localizedRequestingDepartment = DEPARTMENT_MAPPING[locale][c.requestingDepartment] || c.requestingDepartment;
    const localizedRequester = REQUESTER_MAPPING[locale][c.requester] || c.requester;
    const localizedAssignee = c.assignee ? MEMBER_MAPPING[locale][c.assignee] || c.assignee : "";
    const localizedSubAssignee = c.subAssignee ? MEMBER_MAPPING[locale][c.subAssignee] || c.subAssignee : "";
    const localizedContractCategory = c.contractCategory
      ? CONTRACT_CATEGORY_MAPPING[locale][c.contractCategory] || c.contractCategory
      : undefined;

    // statusHistoryも変換
    const localizedStatusHistory = c.statusHistory?.map((sh) => ({
      ...sh,
      status: STATUS_MAPPING[locale][sh.status] || sh.status,
    }));

    return {
      ...c,
      caseName: localizedCaseName,
      status: localizedStatus,
      caseType: localizedCaseType,
      requestingDepartment: localizedRequestingDepartment,
      requester: localizedRequester,
      assignee: localizedAssignee,
      subAssignee: localizedSubAssignee,
      contractCategory: localizedContractCategory,
      statusHistory: localizedStatusHistory,
    } as CaseData;
  });
};

// ロケール対応メンバー名取得関数
export const getLocalizedTeamMembers = (locale: LocaleCode): string[] => {
  return teamMembers.map((member) => MEMBER_MAPPING[locale][member] || member);
};

// 逆マッピング関数（ローカライズされた値から日本語キーに変換）
export const getReverseStatusMapping = (locale: LocaleCode): Record<string, string> => {
  const reverseMap: Record<string, string> = {};
  for (const key in STATUS_MAPPING["ja-JP"]) {
    if (Object.hasOwn(STATUS_MAPPING["ja-JP"], key)) {
      const translatedValue = STATUS_MAPPING[locale][key];
      if (translatedValue) {
        reverseMap[translatedValue] = key;
      }
    }
  }
  return reverseMap;
};

export const getReverseCaseTypeMapping = (locale: LocaleCode): Record<string, string> => {
  const reverseMap: Record<string, string> = {};
  for (const key in CASE_TYPE_MAPPING["ja-JP"]) {
    if (Object.hasOwn(CASE_TYPE_MAPPING["ja-JP"], key)) {
      const translatedValue = CASE_TYPE_MAPPING[locale][key];
      if (translatedValue) {
        reverseMap[translatedValue] = key;
      }
    }
  }
  return reverseMap;
};

// 納期フィルターのマッピング
const DUE_DATE_FILTER_MAPPING: Record<LocaleCode, Record<string, string>> = {
  "ja-JP": {
    すべて: "すべて",
    納期超過: "納期超過",
    今日まで: "今日まで",
    今日含め3日以内: "今日含め3日以内",
    今日含め7日以内: "今日含め7日以内",
    "1週間後〜": "1週間後〜",
    納期未入力: "納期未入力",
  },
  "en-US": {
    すべて: "All",
    納期超過: "Overdue",
    今日まで: "Due today",
    今日含め3日以内: "Within 3 days including today",
    今日含め7日以内: "Within 7 days including today",
    "1週間後〜": "1 week later ~",
    納期未入力: "No due date",
  },
};

export const getReverseDueDateMapping = (locale: LocaleCode): Record<string, string> => {
  const reverseMap: Record<string, string> = {};
  for (const key in DUE_DATE_FILTER_MAPPING["ja-JP"]) {
    if (Object.hasOwn(DUE_DATE_FILTER_MAPPING["ja-JP"], key)) {
      const translatedValue = DUE_DATE_FILTER_MAPPING[locale][key];
      if (translatedValue) {
        reverseMap[translatedValue] = key;
      }
    }
  }
  return reverseMap;
};

// ローカライズされた案件タイプの順序を取得
export const getLocalizedCaseTypeOrder = (locale: LocaleCode): string[] => {
  return CASE_TYPE_ORDER.map((type) => CASE_TYPE_MAPPING[locale][type] || type);
};

// ローカライズされた納期カテゴリの順序を取得（テーブル列のキー用）
export const getLocalizedDueDateCategories = (locale: LocaleCode): string[] => {
  const categories = ["未入力", "超過", "今日", "2日以内", "3-6日以内", "7日以降"];
  const mapping: Record<LocaleCode, Record<string, string>> = {
    "ja-JP": {
      超過: "超過",
      今日: "今日",
      "2日以内": "2日以内",
      "3-6日以内": "3-6日以内",
      "7日以降": "7日以降",
      未入力: "未入力",
    },
    "en-US": {
      超過: "Overdue",
      今日: "Today",
      "2日以内": "Within 2 days",
      "3-6日以内": "Within 3-6 days",
      "7日以降": "7+ days",
      未入力: "Not set",
    },
  };
  return categories.map((category) => mapping[locale][category] || category);
};

export const teamMembers = ["佐藤 陽子", "鈴木 一郎", "高橋 恵子", "田中 健太", "渡辺 直美"];

// ユーザーグループの定義（グループ名と所属ユーザーのマッピング）
export const USER_GROUPS: Record<string, string[]> = {
  法務グループ1: ["佐藤 陽子", "鈴木 一郎"],
  法務グループ2: ["高橋 恵子", "田中 健太"],
  法務グループ3: ["渡辺 直美"],
};

// ユーザーグループ名の多言語対応マッピング
export const USER_GROUP_MAPPING: Record<LocaleCode, Record<string, string>> = {
  "ja-JP": {
    法務グループ1: "法務グループ1",
    法務グループ2: "法務グループ2",
    法務グループ3: "法務グループ3",
  },
  "en-US": {
    法務グループ1: "Legal Group 1",
    法務グループ2: "Legal Group 2",
    法務グループ3: "Legal Group 3",
  },
};

// NOTE: 本来はテナントTZの「今日」を使う（PRD 3.2 B-2 / 7.2.1）。
// このプロトタイプではデモの再現性のため固定日付にしている。
export const today = new Date("2025-12-08"); // Assuming today is 2025-12-08 for consistent demo
today.setHours(0, 0, 0, 0);
