import { promises as fs } from "node:fs";
import path from "node:path";

interface GeneratedPrdParams {
  pageDir: string;
  pageName: string;
  pageDescription: string;
  relativePagePath: string;
}

const GENERATED_PRD_FILE_NAME = "auto-generated-prd.md";

const formatDate = (date: Date): string => {
  return date.toISOString();
};

const buildInitialGeneratedPrd = ({
  pageName,
  pageDescription,
  relativePagePath,
}: Omit<GeneratedPrdParams, "pageDir">): string => {
  const now = formatDate(new Date());

  return `# Auto-Generated PRD - ${pageName}

> **Note:** This file was auto-generated by AI. / このファイルは AI によって自動生成されました。

<!-- AUTO_GENERATED_PRD_VERSION: 1 -->
<!-- GENERATED_AT: ${now} -->
<!-- LAST_UPDATED: ${now} -->
<!-- SANDBOX_PAGE: src/pages/sandbox/${relativePagePath}/index.tsx -->

## Snapshot
- Goal: {TBD}
- Target user: {TBD}
- Main job-to-be-done: {TBD}

## Confirmed Requirements
- {TBD}

## Inferred Requirements
- [confidence: 0.50] {TBD}

## Open Questions
- {TBD}

## UI Mapping (Requirement -> Aegis Component)
- {TBD} -> {TBD}

## Prompt Log
### Initial context
- Page description: ${pageDescription}

## Change Log
- ${now}: File initialized automatically.
`;
};

export const ensureGeneratedPrd = async ({
  pageDir,
  pageName,
  pageDescription,
  relativePagePath,
}: GeneratedPrdParams): Promise<{ created: boolean; filePath: string }> => {
  const filePath = path.join(pageDir, GENERATED_PRD_FILE_NAME);

  try {
    await fs.access(filePath);
    return { created: false, filePath };
  } catch {
    const content = buildInitialGeneratedPrd({ pageName, pageDescription, relativePagePath });
    await fs.writeFile(filePath, content, "utf-8");
    return { created: true, filePath };
  }
};
